pragma Ada_2022;

--  Generated by tools/gen_templates -- do not edit by hand.
--  The fixed, schema-independent code-generator templates, held as
--  string constants so the emitters never hand-escape another language.
package Templates is

   LF : constant Character := ASCII.LF;

   C_Lexer : constant String :=
     "/* ------------------------------------------------------------------ */" & LF &
     "/* Lexer: text -> token stream (schema-independent).  Skips whitespace */" & LF &
     "/* and `#` comments; yields word/string/number/punctuation tokens.     */" & LF &
     "/* ------------------------------------------------------------------ */" & LF &
     "" & LF &
     "typedef struct { token_t *toks; size_t n; } lexed_t;" & LF &
     "" & LF &
     "static int lex_digit(char c) { return c >= '0' && c <= '9'; }" & LF &
     "static int lex_word_start(char c) {" & LF &
     "    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')" & LF &
     "        || c == '_' || c == '-';" & LF &
     "}" & LF &
     "static int lex_word_char(char c) {" & LF &
     "    return lex_word_start(c) || lex_digit(c) || c == '.';" & LF &
     "}" & LF &
     "static char *lex_dup(const char *s, size_t n) {" & LF &
     "    char *p = (char *)malloc(n + 1);" & LF &
     "    if (p) { memcpy(p, s, n); p[n] = '\0'; }" & LF &
     "    return p;" & LF &
     "}" & LF &
     "" & LF &
     "lexed_t lex(const char *text) {" & LF &
     "    lexed_t r = {0};" & LF &
     "    token_t *toks = (token_t *)malloc((strlen(text) + 2) * sizeof *toks);" & LF &
     "    size_t i = 0, line = 1, col = 1;" & LF &
     "" & LF &
     "    while (text[i]) {" & LF &
     "        char c = text[i];" & LF &
     "        if (c == ' ' || c == '\t' || c == '\r') { i++; col++; }" & LF &
     "        else if (c == '\n') { i++; line++; col = 1; }" & LF &
     "        else if (c == '#') { while (text[i] && text[i] != '\n') i++; }" & LF &
     "        else if (c == '""') {" & LF &
     "            size_t sc = col;" & LF &
     "            char *buf = (char *)malloc(strlen(text + i) + 1);" & LF &
     "            size_t bn = 0;" & LF &
     "            i++; col++;" & LF &
     "            while (text[i] && text[i] != '""') {" & LF &
     "                if (text[i] == '\\' && text[i + 1]) { i++; col++; }" & LF &
     "                buf[bn++] = text[i++]; col++;" & LF &
     "            }" & LF &
     "            if (text[i] == '""') { i++; col++; }" & LF &
     "            buf[bn] = '\0';" & LF &
     "            toks[r.n++] = (token_t){ TOK_STR, buf, line, sc };" & LF &
     "        }" & LF &
     "        else if (lex_digit(c)) {" & LF &
     "            size_t s = i, sc = col; int dec = 0;" & LF &
     "            while (lex_digit(text[i])) { i++; col++; }" & LF &
     "            if (text[i] == '.' && lex_digit(text[i + 1])) {" & LF &
     "                dec = 1; i++; col++;" & LF &
     "                while (lex_digit(text[i])) { i++; col++; }" & LF &
     "            }" & LF &
     "            if (text[i] == 'e' || text[i] == 'E') {" & LF &
     "                dec = 1; i++; col++;" & LF &
     "                if (text[i] == '+' || text[i] == '-') { i++; col++; }" & LF &
     "                while (lex_digit(text[i])) { i++; col++; }" & LF &
     "            }" & LF &
     "            toks[r.n++] = (token_t){ dec ? TOK_DEC : TOK_INT," & LF &
     "                                     lex_dup(text + s, i - s), line, sc };" & LF &
     "        }" & LF &
     "        else if (lex_word_start(c)) {" & LF &
     "            size_t s = i, sc = col;" & LF &
     "            while (lex_word_char(text[i])) { i++; col++; }" & LF &
     "            toks[r.n++] = (token_t){ TOK_ATOM, lex_dup(text + s, i - s), line, sc };" & LF &
     "        }" & LF &
     "        else {" & LF &
     "            toks[r.n++] = (token_t){ TOK_PUNCT, lex_dup(text + i, 1), line, col };" & LF &
     "            i++; col++;" & LF &
     "        }" & LF &
     "    }" & LF &
     "    toks[r.n++] = (token_t){ TOK_EOF, lex_dup("""", 0), line, col };" & LF &
     "    r.toks = toks;" & LF &
     "    return r;" & LF &
     "}" & LF &
     "" & LF &
     "/* Convenience: lex, split text into lines (for the caret), then parse. */" & LF &
     "bool parse_text(const char *text, @ROOT_TYPE@ *out," & LF &
     "                char *err, size_t errlen, size_t *err_line, size_t *err_col) {" & LF &
     "    lexed_t l = lex(text);" & LF &
     "    size_t nlines = 1, i, k = 0, s = 0;" & LF &
     "    const char *p;" & LF &
     "    for (p = text; *p; p++) if (*p == '\n') nlines++;" & LF &
     "    char **lines = (char **)malloc(nlines * sizeof *lines);" & LF &
     "    for (i = 0; ; i++) {" & LF &
     "        if (text[i] == '\n' || text[i] == '\0') {" & LF &
     "            lines[k++] = lex_dup(text + s, i - s);" & LF &
     "            if (text[i] == '\0') break;" & LF &
     "            s = i + 1;" & LF &
     "        }" & LF &
     "    }" & LF &
     "    bool ok = parse_tokens(l.toks, l.n, out, (const char *const *)lines, nlines," & LF &
     "                           err, errlen, err_line, err_col);" & LF &
     "    for (i = 0; i < l.n; i++) free((char *)l.toks[i].text);" & LF &
     "    free(l.toks);" & LF &
     "    for (i = 0; i < nlines; i++) free(lines[i]);" & LF &
     "    free(lines);" & LF &
     "    return ok;" & LF &
     "}";

   Rust_Lexer : constant String :=
     "fn lx_digit(c: u8) -> bool { c.is_ascii_digit() }" & LF &
     "fn lx_word_start(c: u8) -> bool { c.is_ascii_alphabetic() || c == b'_' || c == b'-' }" & LF &
     "fn lx_word_char(c: u8) -> bool { lx_word_start(c) || lx_digit(c) || c == b'.' }" & LF &
     "" & LF &
     "pub fn lex(text: &str) -> Vec<Token> {" & LF &
     "    let b = text.as_bytes();" & LF &
     "    let mut toks = Vec::new();" & LF &
     "    let mut i = 0usize; let mut line = 1usize; let mut col = 1usize;" & LF &
     "    while i < b.len() {" & LF &
     "        let c = b[i];" & LF &
     "        if c == b' ' || c == b'\t' || c == b'\r' { i += 1; col += 1; }" & LF &
     "        else if c == b'\n' { i += 1; line += 1; col = 1; }" & LF &
     "        else if c == b'#' { while i < b.len() && b[i] != b'\n' { i += 1; } }" & LF &
     "        else if c == b'""' {" & LF &
     "            let sc = col; let mut s = String::new();" & LF &
     "            i += 1; col += 1;" & LF &
     "            while i < b.len() && b[i] != b'""' {" & LF &
     "                if b[i] == b'\\' && i + 1 < b.len() { i += 1; col += 1; }" & LF &
     "                s.push(b[i] as char); i += 1; col += 1;" & LF &
     "            }" & LF &
     "            if i < b.len() && b[i] == b'""' { i += 1; col += 1; }" & LF &
     "            toks.push(Token { kind: Kind::Str, text: s, line, col: sc });" & LF &
     "        }" & LF &
     "        else if lx_digit(c) {" & LF &
     "            let s = i; let sc = col; let mut dec = false;" & LF &
     "            while i < b.len() && lx_digit(b[i]) { i += 1; col += 1; }" & LF &
     "            if i + 1 < b.len() && b[i] == b'.' && lx_digit(b[i + 1]) {" & LF &
     "                dec = true; i += 1; col += 1;" & LF &
     "                while i < b.len() && lx_digit(b[i]) { i += 1; col += 1; }" & LF &
     "            }" & LF &
     "            if i < b.len() && (b[i] == b'e' || b[i] == b'E') {" & LF &
     "                dec = true; i += 1; col += 1;" & LF &
     "                if i < b.len() && (b[i] == b'+' || b[i] == b'-') { i += 1; col += 1; }" & LF &
     "                while i < b.len() && lx_digit(b[i]) { i += 1; col += 1; }" & LF &
     "            }" & LF &
     "            toks.push(Token { kind: if dec { Kind::Dec } else { Kind::Int }," & LF &
     "                              text: text[s..i].to_string(), line, col: sc });" & LF &
     "        }" & LF &
     "        else if lx_word_start(c) {" & LF &
     "            let s = i; let sc = col;" & LF &
     "            while i < b.len() && lx_word_char(b[i]) { i += 1; col += 1; }" & LF &
     "            toks.push(Token { kind: Kind::Atom, text: text[s..i].to_string(), line, col: sc });" & LF &
     "        }" & LF &
     "        else {" & LF &
     "            toks.push(Token { kind: Kind::Punct, text: (c as char).to_string(), line, col });" & LF &
     "            i += 1; col += 1;" & LF &
     "        }" & LF &
     "    }" & LF &
     "    toks.push(Token { kind: Kind::Eof, text: String::new(), line, col });" & LF &
     "    toks" & LF &
     "}" & LF &
     "" & LF &
     "pub fn parse_text(text: &str) -> Result<@ROOT_TYPE@, ParseError> {" & LF &
     "    let toks = lex(text);" & LF &
     "    let lines: Vec<&str> = text.split('\n').collect();" & LF &
     "    parse_config(&toks, &lines)" & LF &
     "}";

   Zig_Lexer : constant String :=
     "fn lxDigit(c: u8) bool { return c >= '0' and c <= '9'; }" & LF &
     "fn lxWordStart(c: u8) bool {" & LF &
     "    return (c >= 'a' and c <= 'z') or (c >= 'A' and c <= 'Z')" & LF &
     "        or c == '_' or c == '-';" & LF &
     "}" & LF &
     "fn lxWordChar(c: u8) bool { return lxWordStart(c) or lxDigit(c) or c == '.'; }" & LF &
     "" & LF &
     "pub fn lex(alloc: std.mem.Allocator, text: []const u8) ![]Token {" & LF &
     "    var toks = std.ArrayList(Token).empty;" & LF &
     "    var i: usize = 0; var line: usize = 1; var col: usize = 1;" & LF &
     "    while (i < text.len) {" & LF &
     "        const c = text[i];" & LF &
     "        if (c == ' ' or c == '\t' or c == '\r') { i += 1; col += 1; }" & LF &
     "        else if (c == '\n') { i += 1; line += 1; col = 1; }" & LF &
     "        else if (c == '#') { while (i < text.len and text[i] != '\n') i += 1; }" & LF &
     "        else if (c == '""') {" & LF &
     "            const sc = col;" & LF &
     "            var s = std.ArrayList(u8).empty;" & LF &
     "            i += 1; col += 1;" & LF &
     "            while (i < text.len and text[i] != '""') {" & LF &
     "                if (text[i] == '\\' and i + 1 < text.len) { i += 1; col += 1; }" & LF &
     "                try s.append(alloc, text[i]);" & LF &
     "                i += 1; col += 1;" & LF &
     "            }" & LF &
     "            if (i < text.len and text[i] == '""') { i += 1; col += 1; }" & LF &
     "            try toks.append(alloc, .{ .kind = .str, .text = try s.toOwnedSlice(alloc), .line = line, .col = sc });" & LF &
     "        }" & LF &
     "        else if (lxDigit(c)) {" & LF &
     "            const s = i; const sc = col; var dec = false;" & LF &
     "            while (i < text.len and lxDigit(text[i])) { i += 1; col += 1; }" & LF &
     "            if (i + 1 < text.len and text[i] == '.' and lxDigit(text[i + 1])) {" & LF &
     "                dec = true; i += 1; col += 1;" & LF &
     "                while (i < text.len and lxDigit(text[i])) { i += 1; col += 1; }" & LF &
     "            }" & LF &
     "            if (i < text.len and (text[i] == 'e' or text[i] == 'E')) {" & LF &
     "                dec = true; i += 1; col += 1;" & LF &
     "                if (i < text.len and (text[i] == '+' or text[i] == '-')) { i += 1; col += 1; }" & LF &
     "                while (i < text.len and lxDigit(text[i])) { i += 1; col += 1; }" & LF &
     "            }" & LF &
     "            try toks.append(alloc, .{ .kind = if (dec) .dec else .int," & LF &
     "                                     .text = text[s..i], .line = line, .col = sc });" & LF &
     "        }" & LF &
     "        else if (lxWordStart(c)) {" & LF &
     "            const s = i; const sc = col;" & LF &
     "            while (i < text.len and lxWordChar(text[i])) { i += 1; col += 1; }" & LF &
     "            try toks.append(alloc, .{ .kind = .atom, .text = text[s..i], .line = line, .col = sc });" & LF &
     "        }" & LF &
     "        else {" & LF &
     "            try toks.append(alloc, .{ .kind = .punct, .text = text[i..i + 1], .line = line, .col = col });" & LF &
     "            i += 1; col += 1;" & LF &
     "        }" & LF &
     "    }" & LF &
     "    try toks.append(alloc, .{ .kind = .eof, .text = """", .line = line, .col = col });" & LF &
     "    return toks.toOwnedSlice(alloc);" & LF &
     "}" & LF &
     "" & LF &
     "pub fn parse_text(alloc: std.mem.Allocator, text: []const u8," & LF &
     "                  err: *[512]u8, err_line: *usize, err_col: *usize) ParseError!@ROOT_TYPE@ {" & LF &
     "    const toks = try lex(alloc, text);" & LF &
     "    var lines = std.ArrayList([]const u8).empty;" & LF &
     "    var s: usize = 0;" & LF &
     "    for (text, 0..) |ch, idx| {" & LF &
     "        if (ch == '\n') {" & LF &
     "            try lines.append(alloc, text[s..idx]);" & LF &
     "            s = idx + 1;" & LF &
     "        }" & LF &
     "    }" & LF &
     "    try lines.append(alloc, text[s..]);" & LF &
     "    return parse_config(alloc, toks, lines.items, err, err_line, err_col);" & LF &
     "}";

   Ada_Lexer : constant String :=
     "   function Lex (Text : String) return Token_Vectors.Vector is" & LF &
     "      Toks : Token_Vectors.Vector;" & LF &
     "      I    : Natural := Text'First;" & LF &
     "      Line : Natural := 1;" & LF &
     "      Col  : Natural := 1;" & LF &
     "      C    : Character;" & LF &
     "   begin" & LF &
     "      while I <= Text'Last loop" & LF &
     "         C := Text (I);" & LF &
     "         if C = ' ' or else C = ASCII.HT or else C = ASCII.CR then" & LF &
     "            I := I + 1; Col := Col + 1;" & LF &
     "         elsif C = ASCII.LF then" & LF &
     "            I := I + 1; Line := Line + 1; Col := 1;" & LF &
     "         elsif C = '#' then" & LF &
     "            while I <= Text'Last and then Text (I) /= ASCII.LF loop" & LF &
     "               I := I + 1;" & LF &
     "            end loop;" & LF &
     "         elsif C = '""' then" & LF &
     "            declare" & LF &
     "               SC  : constant Natural := Col;" & LF &
     "               Buf : Unbounded_String;" & LF &
     "            begin" & LF &
     "               I := I + 1; Col := Col + 1;" & LF &
     "               while I <= Text'Last and then Text (I) /= '""' loop" & LF &
     "                  if Text (I) = '\' and then I < Text'Last then" & LF &
     "                     I := I + 1; Col := Col + 1;" & LF &
     "                  end if;" & LF &
     "                  Append (Buf, Text (I));" & LF &
     "                  I := I + 1; Col := Col + 1;" & LF &
     "               end loop;" & LF &
     "               if I <= Text'Last then" & LF &
     "                  I := I + 1; Col := Col + 1;" & LF &
     "               end if;" & LF &
     "               Toks.Append (Token'(Str, Buf, Line, SC));" & LF &
     "            end;" & LF &
     "         elsif C in '0' .. '9' then" & LF &
     "            declare" & LF &
     "               SC     : constant Natural := Col;" & LF &
     "               Is_Dec : Boolean := False;" & LF &
     "               Buf    : Unbounded_String;" & LF &
     "            begin" & LF &
     "               while I <= Text'Last and then Text (I) in '0' .. '9' loop" & LF &
     "                  Append (Buf, Text (I)); I := I + 1; Col := Col + 1;" & LF &
     "               end loop;" & LF &
     "               if I < Text'Last and then Text (I) = '.' and then Text (I + 1) in '0' .. '9' then" & LF &
     "                  Is_Dec := True;" & LF &
     "                  Append (Buf, '.'); I := I + 1; Col := Col + 1;" & LF &
     "                  while I <= Text'Last and then Text (I) in '0' .. '9' loop" & LF &
     "                     Append (Buf, Text (I)); I := I + 1; Col := Col + 1;" & LF &
     "                  end loop;" & LF &
     "               end if;" & LF &
     "               if I <= Text'Last and then (Text (I) = 'e' or else Text (I) = 'E') then" & LF &
     "                  Is_Dec := True;" & LF &
     "                  Append (Buf, Text (I)); I := I + 1; Col := Col + 1;" & LF &
     "                  if I <= Text'Last and then (Text (I) = '+' or else Text (I) = '-') then" & LF &
     "                     Append (Buf, Text (I)); I := I + 1; Col := Col + 1;" & LF &
     "                  end if;" & LF &
     "                  while I <= Text'Last and then Text (I) in '0' .. '9' loop" & LF &
     "                     Append (Buf, Text (I)); I := I + 1; Col := Col + 1;" & LF &
     "                  end loop;" & LF &
     "               end if;" & LF &
     "               Toks.Append (Token'((if Is_Dec then Dec else Int), Buf, Line, SC));" & LF &
     "            end;" & LF &
     "         elsif C in 'a' .. 'z' or else C in 'A' .. 'Z' or else C = '_' or else C = '-' then" & LF &
     "            declare" & LF &
     "               SC  : constant Natural := Col;" & LF &
     "               Buf : Unbounded_String;" & LF &
     "            begin" & LF &
     "               while I <= Text'Last loop" & LF &
     "                  C := Text (I);" & LF &
     "                  exit when not (C in 'a' .. 'z' or else C in 'A' .. 'Z'" & LF &
     "                    or else C in '0' .. '9' or else C = '_' or else C = '-'" & LF &
     "                    or else C = '.');" & LF &
     "                  Append (Buf, C); I := I + 1; Col := Col + 1;" & LF &
     "               end loop;" & LF &
     "               Toks.Append (Token'(Atom, Buf, Line, SC));" & LF &
     "            end;" & LF &
     "         else" & LF &
     "            declare" & LF &
     "               Buf : Unbounded_String;" & LF &
     "            begin" & LF &
     "               Append (Buf, C);" & LF &
     "               Toks.Append (Token'(Punct, Buf, Line, Col));" & LF &
     "               I := I + 1; Col := Col + 1;" & LF &
     "            end;" & LF &
     "         end if;" & LF &
     "      end loop;" & LF &
     "      Toks.Append (Token'(Eof, Null_Unbounded_String, Line, Col));" & LF &
     "      return Toks;" & LF &
     "   end Lex;" & LF &
     "" & LF &
     "   function Parse_Text (Text : String) return @ROOT_TYPE@ is" & LF &
     "      Toks  : Token_Vectors.Vector := Lex (Text);" & LF &
     "      Lines : Line_Vectors.Vector;" & LF &
     "      S     : Natural := Text'First;" & LF &
     "   begin" & LF &
     "      for K in Text'Range loop" & LF &
     "         if Text (K) = ASCII.LF then" & LF &
     "            Lines.Append (To_Unbounded_String (Text (S .. K - 1)));" & LF &
     "            S := K + 1;" & LF &
     "         end if;" & LF &
     "      end loop;" & LF &
     "      Lines.Append (To_Unbounded_String (Text (S .. Text'Last)));" & LF &
     "      declare" & LF &
     "         P : Parser := (Toks => Toks, Lines => Lines, Pos => 1);" & LF &
     "         R : @ROOT_TYPE@;" & LF &
     "      begin" & LF &
     "         R := @ROOT_FN@ (P);" & LF &
     "         if P.Pos <= Natural (P.Toks.Length) and then P.Toks (P.Pos).Kind /= Eof then" & LF &
     "            Fail (P, ""end of config"");" & LF &
     "         end if;" & LF &
     "         return R;" & LF &
     "      end;" & LF &
     "   end Parse_Text;";

   Conf_H : constant String :=
     "/* The configuration tree root, populated by parse_config(). */" & LF &
     "extern @ROOT_TYPE@ *conf;" & LF &
     "" & LF &
     "/* Error handler: default prints ""file:line: msg"" and exits; override to" & LF &
     "   handle errors yourself (parse_config then returns -1 instead). */" & LF &
     "typedef void (*conf_error_fn)(const char *file, size_t line, const char *msg);" & LF &
     "extern conf_error_fn conf_error;" & LF &
     "" & LF &
     "/* Read filename, populate the global `conf`.  Returns 0 on success, -1 on" & LF &
     "   error (after calling conf_error). */" & LF &
     "int parse_config(const char *filename);";

   Conf_Tail_C : constant String :=
     "@ROOT_TYPE@ *conf = NULL;" & LF &
     "" & LF &
     "/* Default handler: print ""file:line: <caret message>"" and exit(1).  Override" & LF &
     "   conf_error with your own to take the message elsewhere (then parse_config" & LF &
     "   returns -1 after calling it). */" & LF &
     "static void conf_error_default(const char *file, size_t line, const char *msg) {" & LF &
     "    if (line)" & LF &
     "        fprintf(stderr, ""%s:%zu: %s\n"", file, line, msg);" & LF &
     "    else" & LF &
     "        fprintf(stderr, ""%s: %s\n"", file, msg);" & LF &
     "    exit(1);" & LF &
     "}" & LF &
     "" & LF &
     "conf_error_fn conf_error = conf_error_default;" & LF &
     "" & LF &
     "int parse_config(const char *filename) {" & LF &
     "    FILE *f = fopen(filename, ""r"");" & LF &
     "    char *buf;" & LF &
     "    long len;" & LF &
     "    char err[512];" & LF &
     "    size_t line = 0, col = 0;" & LF &
     "" & LF &
     "    if (!f) {" & LF &
     "        conf_error(filename, 0, ""cannot open file"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    if (fseek(f, 0, SEEK_END) != 0 || (len = ftell(f)) < 0 ||" & LF &
     "        fseek(f, 0, SEEK_SET) != 0) {" & LF &
     "        fclose(f);" & LF &
     "        conf_error(filename, 0, ""cannot read file"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    buf = (char *)malloc((size_t)len + 1);" & LF &
     "    if (!buf) {" & LF &
     "        fclose(f);" & LF &
     "        conf_error(filename, 0, ""out of memory"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    if (len > 0 && fread(buf, 1, (size_t)len, f) != (size_t)len) {" & LF &
     "        free(buf);" & LF &
     "        fclose(f);" & LF &
     "        conf_error(filename, 0, ""read error"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    buf[len] = '\0';" & LF &
     "    fclose(f);" & LF &
     "" & LF &
     "    conf = (@ROOT_TYPE@ *)calloc(1, sizeof *conf);" & LF &
     "    if (!conf) {" & LF &
     "        free(buf);" & LF &
     "        conf_error(filename, 0, ""out of memory"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    if (!parse_text(buf, conf, err, sizeof err, &line, &col)) {" & LF &
     "        free(buf);" & LF &
     "        conf_error(filename, line, err);  /* err carries the caret message */" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    free(buf);" & LF &
     "    return 0;" & LF &
     "}";

   --  Replace every occurrence of From in Text with To.
   function Substitute (Text, From, To : String) return String;

end Templates;
