pragma Ada_2022;

--  Generated by tools/gen_templates -- do not edit by hand.
--  The fixed, schema-independent code-generator templates, held as
--  string constants so the emitters never hand-escape another language.
package Templates is

   LF : constant Character := ASCII.LF;

   C_Lexer : constant String :=
     "/* ------------------------------------------------------------------ */" & LF &
     "/* Lexer: text -> token stream (schema-independent).  Skips whitespace */" & LF &
     "/* and `#` comments; yields word/string/number/punctuation tokens.     */" & LF &
     "/* ------------------------------------------------------------------ */" & LF &
     "" & LF &
     "typedef struct { token_t *toks; size_t n; } lexed_t;" & LF &
     "" & LF &
     "/* Append a token, growing the array geometrically.  Returns 0 when memory" & LF &
     "   runs out; the lexer then gives up and its caller reports it. */" & LF &
     "static int lex_push(lexed_t *r, size_t *cap, token_t t) {" & LF &
     "    if (r->n == *cap) {" & LF &
     "        size_t nc = *cap * 2;" & LF &
     "        token_t *nt = (token_t *)realloc(r->toks, nc * sizeof *nt);" & LF &
     "        if (!nt) return 0;" & LF &
     "        r->toks = nt;" & LF &
     "        *cap = nc;" & LF &
     "    }" & LF &
     "    r->toks[r->n++] = t;" & LF &
     "    return 1;" & LF &
     "}" & LF &
     "" & LF &
     "static int lex_digit(char c) { return c >= '0' && c <= '9'; }" & LF &
     "static int lex_word_start(char c) {" & LF &
     "    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')" & LF &
     "        || c == '_' || c == '-'@WORD_CHARS@;" & LF &
     "}" & LF &
     "static int lex_word_char(char c) {" & LF &
     "    return lex_word_start(c) || lex_digit(c) || c == '.';" & LF &
     "}" & LF &
     "" & LF &
     "/* The token array.  NULL toks (n = 0) means the input could not be" & LF &
     "   lexed: it is over 4 GB (tokens hold 32-bit offsets) or memory ran out." & LF &
     "   Lines are counted from hbnf_line_base (a statement's first line). */" & LF &
     "lexed_t lex(const char *text) {" & LF &
     "    lexed_t r = {0};" & LF &
     "    size_t i = 0, line = hbnf_line_base, col = 1;" & LF &
     "    size_t tlen = strlen(text);" & LF &
     "    /* A first guess of one token per 4 bytes of input (real configs run" & LF &
     "       5-6): usually no regrowth, and a fraction of the old one-per-byte. */" & LF &
     "    size_t cap = tlen / 4 + 16;" & LF &
     "" & LF &
     "    if (tlen > (size_t)UINT32_MAX - 2) return r;" & LF &
     "    r.toks = (token_t *)malloc(cap * sizeof *r.toks);" & LF &
     "    if (!r.toks) return r;" & LF &
     "" & LF &
     "    while (text[i]) {" & LF &
     "        char c = text[i];" & LF &
     "        {" & LF &
     "            /* Hand-written jet scanners (schema `%{ %}` blocks) win first. */" & LF &
     "            tok_kind_t jk;" & LF &
     "            size_t jl = jet_dispatch(text, i, tlen, &jk);" & LF &
     "            if (jl > 0) {" & LF &
     "                if (!lex_push(&r, &cap, (token_t){ .text = text + i, .len = jl, .line = line, .col = col, .kind = jk, .kwid = KWID_NONE })) goto oom;" & LF &
     "                i += jl; col += jl;" & LF &
     "                continue;" & LF &
     "            }" & LF &
     "        }" & LF &
     "        if (c == ' ' || c == '\t' || c == '\r') { i++; col++; }" & LF &
     "        else if (c == '\n') { i++; line++; col = 1; }" & LF &
     "        /* backslash-newline continues the line, as parse.y's lgetc() */" & LF &
     "        else if (c == '\\' && text[i + 1] == '\n') { i += 2; line++; col = 1; }" & LF &
     "        else if (c == '#') { while (text[i] && text[i] != '\n') i++; }" & LF &
     "        else if (c == '""') {" & LF &
     "            size_t sc = col, sl = line;" & LF &
     "            i++; col++;" & LF &
     "            while (text[i] && text[i] != '""') {" & LF &
     "                /* inside quotes parse.y drops backslash-newline and a bare" & LF &
     "                   newline alike, counting the line */" & LF &
     "                if (text[i] == '\\' && text[i + 1] == '\n') { i += 2; line++; col = 1; continue; }" & LF &
     "                if (text[i] == '\n') { i++; line++; col = 1; continue; }" & LF &
     "                if (text[i] == '\\' && text[i + 1]) { i++; col++; }" & LF &
     "                hbnf_str_put(text[i++]); col++;" & LF &
     "            }" & LF &
     "            if (text[i] == '""') { i++; col++; }" & LF &
     "            { size_t n = hbnf_scratch_len;" & LF &
     "              const char *s = hbnf_str_append(hbnf_scratch, n);" & LF &
     "              hbnf_scratch_len = 0;" & LF &
     "              if (!lex_push(&r, &cap, (token_t){ .text = s, .len = n, .line = sl, .col = sc, .kind = TOK_STR, .kwid = KWID_NONE })) goto oom; }" & LF &
     "        }" & LF &
     "        else if (lex_digit(c) || (c == '-' && lex_digit(text[i + 1]))) {" & LF &
     "            /* -N is a number too, as in parse.y's lexers */" & LF &
     "            size_t s = i, sc = col;" & LF &
     "            if (c == '-') { i++; col++; }" & LF &
     "            while (lex_digit(text[i])) { i++; col++; }" & LF &
     "            if (lex_word_char(text[i])) {" & LF &
     "                /* dotted/alphanumeric run (1.2.3.4, 123abc) is one word */" & LF &
     "                i = s; col = sc;" & LF &
     "                while (lex_word_char(text[i])) { i++; col++; }" & LF &
     "                if (!lex_push(&r, &cap, (token_t){ .text = text + s, .len = i - s, .line = line, .col = sc, .kind = TOK_ATOM, .kwid = kw_lookup(text + s, i - s) })) goto oom;" & LF &
     "            } else {" & LF &
     "                if (!lex_push(&r, &cap, (token_t){ .text = text + s, .len = i - s, .line = line, .col = sc, .kind = TOK_INT, .kwid = KWID_NONE })) goto oom;" & LF &
     "            }" & LF &
     "        }" & LF &
     "        else if (lex_word_start(c)) {" & LF &
     "            size_t s = i, sc = col;" & LF &
     "            while (lex_word_char(text[i])) { i++; col++; }" & LF &
     "            if (!lex_push(&r, &cap, (token_t){ .text = text + s, .len = i - s, .line = line, .col = sc, .kind = TOK_ATOM, .kwid = kw_lookup(text + s, i - s) })) goto oom;" & LF &
     "        }" & LF &
     "        else {" & LF &
     "            if (!lex_push(&r, &cap, (token_t){ .text = text + i, .len = 1, .line = line, .col = col, .kind = TOK_PUNCT, .kwid = KWID_NONE })) goto oom;" & LF &
     "            i++; col++;" & LF &
     "        }" & LF &
     "    }" & LF &
     "    if (!lex_push(&r, &cap, (token_t){ .text = """", .len = 0, .line = line, .col = col, .kind = TOK_EOF, .kwid = KWID_NONE })) goto oom;" & LF &
     "    return r;" & LF &
     "oom:" & LF &
     "    free(r.toks);" & LF &
     "    r.toks = NULL;" & LF &
     "    r.n = 0;" & LF &
     "    return r;" & LF &
     "}";

   C_Parse_Text : constant String :=
     "/* Convenience: lex, then parse (the caret line is drawn lazily on error). */" & LF &
     "bool parse_text(const char *text, @ROOT_TYPE@ *out," & LF &
     "                char *err, size_t errlen, size_t *err_line, size_t *err_col) {" & LF &
     "    lexed_t l = lex(text);" & LF &
     "    if (!l.toks) {" & LF &
     "        snprintf(err, errlen, ""%s"", strlen(text) > (size_t)UINT32_MAX - 2" & LF &
     "                 ? ""input too large"" : ""out of memory"");" & LF &
     "        *err_line = *err_col = 0;" & LF &
     "        return false;" & LF &
     "    }" & LF &
     "    bool ok = parse_tokens(l.toks, l.n, out, text," & LF &
     "                           err, errlen, err_line, err_col);" & LF &
     "    free(l.toks);" & LF &
     "    return ok;" & LF &
     "}";

   C_Statements : constant String :=
     "/* ------------------------------------------------------------------ */" & LF &
     "/* Statements (the grammar's `statements` directive): the config is    */" & LF &
     "/* read one statement at a time, as parse.y's yyparse reads it.  A     */" & LF &
     "/* statement ends at a newline outside braces, quotes and comments;    */" & LF &
     "/* backslash-newline continues it, and so does a next line that starts */" & LF &
     "/* with `{`.  A file is read in blocks, not whole.  Each statement is  */" & LF &
     "/* expanded (macros), lexed, parsed, bound and then appended to the    */" & LF &
     "/* caller's list, or dropped once the action jets have taken what they */" & LF &
     "/* keep, so only one statement's text, tokens (and nodes) are held at  */" & LF &
     "/* a time.  A failed statement is reported and the parse goes on with  */" & LF &
     "/* the next one, as parse.y's error rule does.                         */" & LF &
     "/* ------------------------------------------------------------------ */" & LF &
     "" & LF &
     "/* Each error as it is found (parse_config points it at conf_error), and" & LF &
     "   the file being read: NULL for the top file, else the included one. */" & LF &
     "static void (*hbnf_report)(size_t line, const char *msg);" & LF &
     "static const char *hbnf_file;" & LF &
     "" & LF &
     "/* Macro hooks: macros.c, or stubs for a grammar without `macros`. */" & LF &
     "static char *hbnf_expand(const char *s, size_t len, char *msg, size_t msglen);" & LF &
     "static void hbnf_trail(char *msg, size_t msglen, size_t line, size_t col);" & LF &
     "static void hbnf_define(const token_t *toks, size_t n, size_t line);" & LF &
     "static void hbnf_macros_done(void);" & LF &
     "" & LF &
     "static char *hbnf_strndup(const char *s, size_t n) {" & LF &
     "    char *d = (char *)malloc(n + 1);" & LF &
     "" & LF &
     "    if (!d)" & LF &
     "        hbnf_oom();" & LF &
     "    memcpy(d, s, n);" & LF &
     "    d[n] = '\0';" & LF &
     "    return d;" & LF &
     "}" & LF &
     "" & LF &
     "typedef struct {" & LF &
     "    @ROOT_TYPE@ *out;          /* the caller's list; NULL: keep nothing */" & LF &
     "    char *err;                 /* the first error, for the caller */" & LF &
     "    size_t errlen;" & LF &
     "    size_t *err_line, *err_col;" & LF &
     "    size_t errors;" & LF &
     "    size_t top_line;           /* the top file's current statement */" & LF &
     "} hbnf_run_t;" & LF &
     "" & LF &
     "/* Count an error, report it unless an action jet already has, and keep" & LF &
     "   the first for the caller: in an included file, as ""file:line: msg"" on" & LF &
     "   the line of the top file's include. */" & LF &
     "static void hbnf_error(hbnf_run_t *r, size_t line, size_t col," & LF &
     "                       const char *msg, int reported) {" & LF &
     "    r->errors++;" & LF &
     "    if (!reported && hbnf_report)" & LF &
     "        hbnf_report(line, msg);" & LF &
     "    if (r->errors > 1)" & LF &
     "        return;" & LF &
     "    if (hbnf_file) {" & LF &
     "        snprintf(r->err, r->errlen, ""%s:%zu: %s"", hbnf_file, line, msg);" & LF &
     "        *r->err_line = r->top_line;" & LF &
     "        *r->err_col = 0;" & LF &
     "    } else {" & LF &
     "        snprintf(r->err, r->errlen, ""%s"", msg);" & LF &
     "        *r->err_line = line;" & LF &
     "        *r->err_col = col;" & LF &
     "    }" & LF &
     "}" & LF &
     "" & LF &
     "/* Where statements come from: a file, read a block at a time, or a" & LF &
     "   string.  Characters read ahead and not used are given back. */" & LF &
     "enum { HBNF_BLOCK = 65536 };" & LF &
     "" & LF &
     "typedef struct {" & LF &
     "    FILE *f;                   /* the file, or NULL for a string */" & LF &
     "    const char *p, *end;       /* the unread part of the block (or string) */" & LF &
     "    char *blk;                 /* the block, for a file */" & LF &
     "    char *back;                /* given back, last in first out */" & LF &
     "    size_t nback, capback;" & LF &
     "    int err;                   /* the file could not be read */" & LF &
     "} hbnf_src_t;" & LF &
     "" & LF &
     "static void hbnf_src_file(hbnf_src_t *s, FILE *f) {" & LF &
     "    memset(s, 0, sizeof *s);" & LF &
     "    s->f = f;" & LF &
     "    s->blk = (char *)malloc(HBNF_BLOCK);" & LF &
     "    if (!s->blk)" & LF &
     "        hbnf_oom();" & LF &
     "}" & LF &
     "" & LF &
     "static void hbnf_src_done(hbnf_src_t *s) {" & LF &
     "    free(s->blk);" & LF &
     "    free(s->back);" & LF &
     "}" & LF &
     "" & LF &
     "static int hbnf_getc(hbnf_src_t *s) {" & LF &
     "    if (s->nback)" & LF &
     "        return (unsigned char)s->back[--s->nback];" & LF &
     "    if (s->p == s->end) {" & LF &
     "        size_t n;" & LF &
     "        if (!s->f)" & LF &
     "            return EOF;" & LF &
     "        n = fread(s->blk, 1, HBNF_BLOCK, s->f);" & LF &
     "        if (n == 0) {" & LF &
     "            if (ferror(s->f))" & LF &
     "                s->err = 1;" & LF &
     "            return EOF;" & LF &
     "        }" & LF &
     "        s->p = s->blk;" & LF &
     "        s->end = s->blk + n;" & LF &
     "    }" & LF &
     "    return (unsigned char)*s->p++;" & LF &
     "}" & LF &
     "" & LF &
     "static void hbnf_ungetc(hbnf_src_t *s, int c) {" & LF &
     "    if (c == EOF)" & LF &
     "        return;" & LF &
     "    if (s->nback == s->capback) {" & LF &
     "        size_t nc = s->capback ? s->capback * 2 : 64;" & LF &
     "        char *nb = (char *)realloc(s->back, nc);" & LF &
     "        if (!nb)" & LF &
     "            hbnf_oom();" & LF &
     "        s->back = nb;" & LF &
     "        s->capback = nc;" & LF &
     "    }" & LF &
     "    s->back[s->nback++] = (char)c;" & LF &
     "}" & LF &
     "" & LF &
     "/* One statement's text, reused from statement to statement. */" & LF &
     "typedef struct {" & LF &
     "    char *s;" & LF &
     "    size_t len, cap;" & LF &
     "} hbnf_buf_t;" & LF &
     "" & LF &
     "static void hbnf_buf_grow(hbnf_buf_t *b, size_t n) {" & LF &
     "    if (b->len + n + 1 > b->cap) {" & LF &
     "        size_t nc = b->cap ? b->cap * 2 : 256;" & LF &
     "        char *ns;" & LF &
     "        while (nc < b->len + n + 1)" & LF &
     "            nc *= 2;" & LF &
     "        if (!(ns = (char *)realloc(b->s, nc)))" & LF &
     "            hbnf_oom();" & LF &
     "        b->s = ns;" & LF &
     "        b->cap = nc;" & LF &
     "    }" & LF &
     "}" & LF &
     "" & LF &
     "static void hbnf_buf_put(hbnf_buf_t *b, int c) {" & LF &
     "    hbnf_buf_grow(b, 1);" & LF &
     "    b->s[b->len++] = (char)c;" & LF &
     "}" & LF &
     "" & LF &
     "enum { HBNF_NO_MORE, HBNF_AT_NEWLINE, HBNF_AT_END };" & LF &
     "" & LF &
     "/* Read the next statement into b, NUL-terminated: up to the newline that" & LF &
     "   ends it, which is read and not kept.  *nl counts the newlines inside" & LF &
     "   it; *empty is set when it holds only blanks and comments.  Quotes and" & LF &
     "   comments are read as the lexer reads them, so a brace in either does" & LF &
     "   not count.  Returns what ended it: a newline, the end of the input, or" & LF &
     "   HBNF_NO_MORE when there was nothing left to read. */" & LF &
     "static int hbnf_read_stmt(hbnf_src_t *s, hbnf_buf_t *b, size_t *nl," & LF &
     "                          int *empty) {" & LF &
     "    long depth = 0;" & LF &
     "    int c, any = 0;" & LF &
     "" & LF &
     "    b->len = 0;" & LF &
     "    *nl = 0;" & LF &
     "    *empty = 1;" & LF &
     "    for (;;) {" & LF &
     "        if (!s->nback && s->p < s->end) {" & LF &
     "            /* a run of characters that need no care, copied at once */" & LF &
     "            const char *q = s->p;" & LF &
     "            while (q < s->end && *q != '\n' && *q != '\\' && *q != '#'" & LF &
     "                   && *q != '""' && *q != '{' && *q != '}') {" & LF &
     "                if (*q != ' ' && *q != '\t' && *q != '\r')" & LF &
     "                    *empty = 0;" & LF &
     "                q++;" & LF &
     "            }" & LF &
     "            if (q > s->p) {" & LF &
     "                hbnf_buf_grow(b, (size_t)(q - s->p));" & LF &
     "                memcpy(b->s + b->len, s->p, (size_t)(q - s->p));" & LF &
     "                b->len += (size_t)(q - s->p);" & LF &
     "                s->p = q;" & LF &
     "                any = 1;" & LF &
     "                continue;" & LF &
     "            }" & LF &
     "        }" & LF &
     "        c = hbnf_getc(s);" & LF &
     "        if (c == EOF)" & LF &
     "            break;" & LF &
     "        any = 1;" & LF &
     "        if (c == '\n') {" & LF &
     "            if (depth <= 0) {" & LF &
     "                /* a `{` opening the next line continues this statement;" & LF &
     "                   anything else there starts the next one */" & LF &
     "                size_t keep = b->len;" & LF &
     "                int d;" & LF &
     "                if (*empty)" & LF &
     "                    goto at_newline;" & LF &
     "                hbnf_buf_put(b, '\n');" & LF &
     "                while ((d = hbnf_getc(s)) == ' ' || d == '\t' || d == '\r')" & LF &
     "                    hbnf_buf_put(b, d);" & LF &
     "                hbnf_ungetc(s, d);" & LF &
     "                if (d != '{') {" & LF &
     "                    while (b->len > keep + 1)" & LF &
     "                        hbnf_ungetc(s, (unsigned char)b->s[--b->len]);" & LF &
     "                    b->len = keep;" & LF &
     "                    goto at_newline;" & LF &
     "                }" & LF &
     "                (*nl)++;" & LF &
     "                continue;" & LF &
     "            }" & LF &
     "            (*nl)++;" & LF &
     "            hbnf_buf_put(b, c);" & LF &
     "        } else if (c == '\\') {" & LF &
     "            int d = hbnf_getc(s);" & LF &
     "            hbnf_buf_put(b, c);" & LF &
     "            if (d == '\n') {" & LF &
     "                (*nl)++;" & LF &
     "                hbnf_buf_put(b, d);" & LF &
     "            } else {" & LF &
     "                *empty = 0;" & LF &
     "                hbnf_ungetc(s, d);" & LF &
     "            }" & LF &
     "        } else if (c == '#') {" & LF &
     "            do" & LF &
     "                hbnf_buf_put(b, c);" & LF &
     "            while ((c = hbnf_getc(s)) != EOF && c != '\n');" & LF &
     "            hbnf_ungetc(s, c);" & LF &
     "        } else if (c == ' ' || c == '\t' || c == '\r') {" & LF &
     "            hbnf_buf_put(b, c);" & LF &
     "        } else if (c == '""') {" & LF &
     "            *empty = 0;" & LF &
     "            hbnf_buf_put(b, c);" & LF &
     "            while ((c = hbnf_getc(s)) != EOF) {" & LF &
     "                hbnf_buf_put(b, c);" & LF &
     "                if (c == '""')" & LF &
     "                    break;" & LF &
     "                if (c == '\\') {" & LF &
     "                    if ((c = hbnf_getc(s)) == EOF)" & LF &
     "                        break;" & LF &
     "                    hbnf_buf_put(b, c);" & LF &
     "                }" & LF &
     "                if (c == '\n')" & LF &
     "                    (*nl)++;" & LF &
     "            }" & LF &
     "        } else {" & LF &
     "            *empty = 0;" & LF &
     "            if (c == '{')" & LF &
     "                depth++;" & LF &
     "            else if (c == '}')" & LF &
     "                depth--;" & LF &
     "            hbnf_buf_put(b, c);" & LF &
     "        }" & LF &
     "    }" & LF &
     "    hbnf_buf_put(b, '\0');" & LF &
     "    b->len--;" & LF &
     "    return any ? HBNF_AT_END : HBNF_NO_MORE;" & LF &
     "at_newline:" & LF &
     "    hbnf_buf_put(b, '\0');" & LF &
     "    b->len--;" & LF &
     "    return HBNF_AT_NEWLINE;" & LF &
     "}" & LF &
     "" & LF &
     "static void hbnf_run(hbnf_run_t *r, hbnf_src_t *src, int depth);" & LF &
     "" & LF &
     "/* An `include`: read the file's statements in its place. */" & LF &
     "static void hbnf_include(hbnf_run_t *r, const char *path, size_t line," & LF &
     "                         int depth) {" & LF &
     "    char msg[512];" & LF &
     "    const char *outer = hbnf_file;" & LF &
     "    hbnf_src_t src;" & LF &
     "    FILE *f;" & LF &
     "" & LF &
     "    if (depth >= 16) {" & LF &
     "        snprintf(msg, sizeof msg, ""%s: includes nested too deeply"", path);" & LF &
     "        hbnf_error(r, line, 0, msg, 0);" & LF &
     "        return;" & LF &
     "    }" & LF &
     "    if (!(f = fopen(path, ""r""))) {" & LF &
     "        snprintf(msg, sizeof msg, ""failed to include file %s"", path);" & LF &
     "        hbnf_error(r, line, 0, msg, 0);" & LF &
     "        return;" & LF &
     "    }" & LF &
     "    hbnf_src_file(&src, f);" & LF &
     "    hbnf_file = path;" & LF &
     "    hbnf_run(r, &src, depth + 1);" & LF &
     "    hbnf_file = outer;" & LF &
     "    hbnf_src_done(&src);" & LF &
     "    fclose(f);" & LF &
     "}" & LF &
     "" & LF &
     "/* One statement, s[0..len), which starts on line `line` of its file. */" & LF &
     "static void hbnf_stmt(hbnf_run_t *r, const char *s, size_t len, size_t line," & LF &
     "                      int depth) {" & LF &
     "    char msg[512];" & LF &
     "    char *buf, *inc = NULL;" & LF &
     "    lexed_t l;" & LF &
     "    @ROOT_TYPE@ part;" & LF &
     "    size_t el = 0, ec = 0;" & LF &
     "    bool ok;" & LF &
     "" & LF &
     "    buf = hbnf_expand(s, len, msg, sizeof msg);" & LF &
     "    if (!buf) {" & LF &
     "        hbnf_error(r, line, 0, msg, 0);" & LF &
     "        return;" & LF &
     "    }" & LF &
     "    hbnf_line_base = line;" & LF &
     "    l = lex(buf);" & LF &
     "    if (!l.toks) {" & LF &
     "        hbnf_line_base = 1;" & LF &
     "        free(buf);" & LF &
     "        hbnf_error(r, line, 0, len > (size_t)UINT32_MAX - 2" & LF &
     "                   ? ""input too large"" : ""out of memory"", 0);" & LF &
     "        return;" & LF &
     "    }" & LF &
     "    hbnf_part_init(&part);" & LF &
     "    ok = parse_tokens(l.toks, l.n, &part, buf, msg, sizeof msg, &el, &ec);" & LF &
     "    hbnf_line_base = 1;" & LF &
     "    if (ok) {" & LF &
     "        const token_t *t = hbnf_include_tok(l.toks, l.n);" & LF &
     "        hbnf_define(l.toks, l.n, line);" & LF &
     "        if (t)" & LF &
     "            inc = hbnf_strndup(t->text, t->len);" & LF &
     "    } else {" & LF &
     "        if (el < line)" & LF &
     "            el = line;" & LF &
     "        hbnf_trail(msg, sizeof msg, el - line, ec);" & LF &
     "        hbnf_error(r, el, ec, msg, hbnf_bind_reported());" & LF &
     "    }" & LF &
     "    if (!r->out)" & LF &
     "        hbnf_part_free(&part);       /* the nodes and the string arena */" & LF &
     "    else if (ok)" & LF &
     "        hbnf_part_move(r->out, &part);" & LF &
     "    else" & LF &
     "        hbnf_part_drop(&part);" & LF &
     "    free(l.toks);" & LF &
     "    free(buf);" & LF &
     "    if (inc) {" & LF &
     "        hbnf_include(r, inc, line, depth);" & LF &
     "        free(inc);" & LF &
     "    }" & LF &
     "}" & LF &
     "" & LF &
     "/* Every statement of one file (or string). */" & LF &
     "static void hbnf_run(hbnf_run_t *r, hbnf_src_t *src, int depth) {" & LF &
     "    hbnf_buf_t b;" & LF &
     "    size_t line = 1, nl;" & LF &
     "    int empty, end;" & LF &
     "" & LF &
     "    memset(&b, 0, sizeof b);" & LF &
     "    while ((end = hbnf_read_stmt(src, &b, &nl, &empty)) != HBNF_NO_MORE) {" & LF &
     "        if (!empty) {" & LF &
     "            if (!depth)" & LF &
     "                r->top_line = line;" & LF &
     "            hbnf_stmt(r, b.s, b.len, line, depth);" & LF &
     "        }" & LF &
     "        line += nl;" & LF &
     "        if (end == HBNF_AT_END)" & LF &
     "            break;" & LF &
     "        line++;" & LF &
     "    }" & LF &
     "    free(b.s);" & LF &
     "    if (src->err)" & LF &
     "        hbnf_error(r, line, 0, ""read error"", 0);" & LF &
     "}" & LF &
     "" & LF &
     "/* Read a config: each statement is appended to *out, or with out NULL" & LF &
     "   dropped once bound.  err, *err_line and *err_col hold the first error;" & LF &
     "   false if there was any. */" & LF &
     "static bool hbnf_stmts(hbnf_src_t *src, @ROOT_TYPE@ *out," & LF &
     "                       char *err, size_t errlen," & LF &
     "                       size_t *err_line, size_t *err_col) {" & LF &
     "    hbnf_run_t r;" & LF &
     "" & LF &
     "    memset(&r, 0, sizeof r);" & LF &
     "    r.out = out;" & LF &
     "    r.err = err;" & LF &
     "    r.errlen = errlen;" & LF &
     "    r.err_line = err_line;" & LF &
     "    r.err_col = err_col;" & LF &
     "    if (errlen)" & LF &
     "        err[0] = '\0';" & LF &
     "    *err_line = *err_col = 0;" & LF &
     "    hbnf_file = NULL;" & LF &
     "    hbnf_run(&r, src, 0);" & LF &
     "    hbnf_macros_done();" & LF &
     "    return r.errors == 0;" & LF &
     "}";

   C_Stmt_Text : constant String :=
     "/* A string as a source of statements (parse_text's). */" & LF &
     "static void hbnf_src_text(hbnf_src_t *s, const char *text) {" & LF &
     "    memset(s, 0, sizeof *s);" & LF &
     "    s->p = text;" & LF &
     "    s->end = text + strlen(text);" & LF &
     "}" & LF &
     "" & LF &
     "/* Parse a whole config into *out (initialized here), one statement at a" & LF &
     "   time.  err, *err_line and *err_col hold the first error (the parse goes" & LF &
     "   on past it); false if there was any. */" & LF &
     "bool parse_text(const char *text, @ROOT_TYPE@ *out," & LF &
     "                char *err, size_t errlen, size_t *err_line, size_t *err_col) {" & LF &
     "    hbnf_src_t src;" & LF &
     "    bool ok;" & LF &
     "" & LF &
     "    hbnf_part_init(out);" & LF &
     "    hbnf_src_text(&src, text);" & LF &
     "    ok = hbnf_stmts(&src, out, err, errlen, err_line, err_col);" & LF &
     "    hbnf_src_done(&src);" & LF &
     "    return ok;" & LF &
     "}" & LF &
     "" & LF &
     "/* The same for a file, read a block at a time rather than whole. */" & LF &
     "bool parse_file(const char *path, @ROOT_TYPE@ *out," & LF &
     "                char *err, size_t errlen, size_t *err_line, size_t *err_col) {" & LF &
     "    hbnf_src_t src;" & LF &
     "    FILE *f;" & LF &
     "    bool ok;" & LF &
     "" & LF &
     "    hbnf_part_init(out);" & LF &
     "    if (!(f = fopen(path, ""r""))) {" & LF &
     "        snprintf(err, errlen, ""cannot open file"");" & LF &
     "        *err_line = *err_col = 0;" & LF &
     "        return false;" & LF &
     "    }" & LF &
     "    hbnf_src_file(&src, f);" & LF &
     "    ok = hbnf_stmts(&src, out, err, errlen, err_line, err_col);" & LF &
     "    hbnf_src_done(&src);" & LF &
     "    fclose(f);" & LF &
     "    return ok;" & LF &
     "}";

   C_Macros : constant String :=
     "/* ------------------------------------------------------------------ */" & LF &
     "/* Macros (the grammar's `macros` directive), as parse.y has them.  A   */" & LF &
     "/* statement the macros rule matches whole defines one: its first token */" & LF &
     "/* is the name, and the tokens after `=`, joined by spaces, the value.  */" & LF &
     "/* `$name` at the start of a word, outside quotes and comments, expands */" & LF &
     "/* to the value, glued to what follows (`$net.5`) and not expanded      */" & LF &
     "/* again.  cmdline_symset(""name=value"") (-D) defines one the config     */" & LF &
     "/* cannot redefine; the others are dropped when the parse ends.         */" & LF &
     "/* ------------------------------------------------------------------ */" & LF &
     "" & LF &
     "typedef struct hbnf_sym {" & LF &
     "    struct hbnf_sym *next;" & LF &
     "    char *nam, *val;" & LF &
     "    char *file;         /* where it was defined: NULL for the top file */" & LF &
     "    size_t line;        /* 0: the command line */" & LF &
     "    int persist;" & LF &
     "} hbnf_sym;" & LF &
     "" & LF &
     "static hbnf_sym *hbnf_syms;" & LF &
     "" & LF &
     "/* Where each expansion in the current statement landed (its line within" & LF &
     "   the statement, its columns), for the trail on an error inside one. */" & LF &
     "typedef struct {" & LF &
     "    size_t line, col0, col1;" & LF &
     "    const hbnf_sym *sym;" & LF &
     "} hbnf_seg;" & LF &
     "" & LF &
     "static hbnf_seg hbnf_segs[16];" & LF &
     "static size_t hbnf_nsegs;" & LF &
     "" & LF &
     "static void hbnf_sym_free(hbnf_sym *y) {" & LF &
     "    free(y->nam);" & LF &
     "    free(y->val);" & LF &
     "    free(y->file);" & LF &
     "    free(y);" & LF &
     "}" & LF &
     "" & LF &
     "static hbnf_sym *hbnf_symget(const char *nam, size_t len) {" & LF &
     "    hbnf_sym *y;" & LF &
     "" & LF &
     "    for (y = hbnf_syms; y; y = y->next)" & LF &
     "        if (strlen(y->nam) == len && memcmp(y->nam, nam, len) == 0)" & LF &
     "            return y;" & LF &
     "    return NULL;" & LF &
     "}" & LF &
     "" & LF &
     "/* parse.y's symset: a command-line macro is not redefined. */" & LF &
     "static int hbnf_symset(const char *nam, size_t len, const char *val," & LF &
     "                       int persist, size_t line) {" & LF &
     "    hbnf_sym *y = hbnf_symget(nam, len), **pp;" & LF &
     "" & LF &
     "    if (y) {" & LF &
     "        if (y->persist)" & LF &
     "            return 0;" & LF &
     "        for (pp = &hbnf_syms; *pp != y; pp = &(*pp)->next)" & LF &
     "            ;" & LF &
     "        *pp = y->next;" & LF &
     "        hbnf_sym_free(y);" & LF &
     "    }" & LF &
     "    y = (hbnf_sym *)calloc(1, sizeof *y);" & LF &
     "    if (!y)" & LF &
     "        hbnf_oom();" & LF &
     "    y->nam = hbnf_strndup(nam, len);" & LF &
     "    y->val = hbnf_strndup(val, strlen(val));" & LF &
     "    y->file = hbnf_file ? hbnf_strndup(hbnf_file, strlen(hbnf_file)) : NULL;" & LF &
     "    y->line = line;" & LF &
     "    y->persist = persist;" & LF &
     "    y->next = hbnf_syms;" & LF &
     "    hbnf_syms = y;" & LF &
     "    return 0;" & LF &
     "}" & LF &
     "" & LF &
     "/* -D name=value: the name ends at the last `=`, as in parse.y. */" & LF &
     "int cmdline_symset(char *s) {" & LF &
     "    const char *val = strrchr(s, '=');" & LF &
     "" & LF &
     "    if (!val)" & LF &
     "        return -1;" & LF &
     "    return hbnf_symset(s, (size_t)(val - s), val + 1, 1, 0);" & LF &
     "}" & LF &
     "" & LF &
     "/* A statement the macros rule matched: remember name = value. */" & LF &
     "static void hbnf_define(const token_t *toks, size_t n, size_t line) {" & LF &
     "    size_t i, eq, len = 0;" & LF &
     "    char *val, *p;" & LF &
     "" & LF &
     "    if (!hbnf_is_macro(toks, n))" & LF &
     "        return;" & LF &
     "    for (eq = 1; eq < n; eq++)" & LF &
     "        if (toks[eq].kind == TOK_PUNCT && toks[eq].len == 1" & LF &
     "            && toks[eq].text[0] == '=')" & LF &
     "            break;" & LF &
     "    for (i = eq + 1; i < n && toks[i].kind != TOK_EOF; i++)" & LF &
     "        len += toks[i].len + 1;" & LF &
     "    val = p = (char *)malloc(len + 1);" & LF &
     "    if (!val)" & LF &
     "        hbnf_oom();" & LF &
     "    for (i = eq + 1; i < n && toks[i].kind != TOK_EOF; i++) {" & LF &
     "        size_t k;" & LF &
     "        if (p != val)" & LF &
     "            *p++ = ' ';" & LF &
     "        for (k = 0; k < toks[i].len; k++)   /* a value is one line */" & LF &
     "            *p++ = toks[i].text[k] == '\n' ? ' ' : toks[i].text[k];" & LF &
     "    }" & LF &
     "    *p = '\0';" & LF &
     "    hbnf_symset(toks[0].text, toks[0].len, val, 0, line);" & LF &
     "    free(val);" & LF &
     "}" & LF &
     "" & LF &
     "/* Append s[0..n) to the growing buffer *o. */" & LF &
     "static void hbnf_put(char **o, size_t *used, size_t *cap, const char *s," & LF &
     "                     size_t n) {" & LF &
     "    if (*used + n + 1 > *cap) {" & LF &
     "        size_t nc = (*used + n + 1) * 2;" & LF &
     "        char *no = (char *)realloc(*o, nc);" & LF &
     "        if (!no)" & LF &
     "            hbnf_oom();" & LF &
     "        *o = no;" & LF &
     "        *cap = nc;" & LF &
     "    }" & LF &
     "    memcpy(*o + *used, s, n);" & LF &
     "    *used += n;" & LF &
     "}" & LF &
     "" & LF &
     "/* The statement s[0..len) with its macros expanded, NUL-terminated;" & LF &
     "   NULL, with msg, if one is not defined. */" & LF &
     "static char *hbnf_expand(const char *s, size_t len, char *msg, size_t msglen) {" & LF &
     "    size_t cap = len + 1, used = 0, i = 0, line = 0, col = 1;" & LF &
     "    char *o = (char *)malloc(cap);" & LF &
     "" & LF &
     "    if (!o)" & LF &
     "        hbnf_oom();" & LF &
     "    hbnf_nsegs = 0;" & LF &
     "    if (!memchr(s, '$', len)) {                 /* most statements */" & LF &
     "        memcpy(o, s, len);" & LF &
     "        o[len] = '\0';" & LF &
     "        return o;" & LF &
     "    }" & LF &
     "    while (i < len) {" & LF &
     "        char c = s[i];" & LF &
     "        size_t j = i + 1;" & LF &
     "        if (c != '""' && c != '#' && c != '$' && c != '\n') {" & LF &
     "            while (j < len && s[j] != '""' && s[j] != '#' && s[j] != '$'" & LF &
     "                   && s[j] != '\n')" & LF &
     "                j++;" & LF &
     "            hbnf_put(&o, &used, &cap, s + i, j - i);" & LF &
     "            col += j - i;" & LF &
     "            i = j;" & LF &
     "            continue;" & LF &
     "        }" & LF &
     "        if (c == '""') {                         /* a quoted string, as is */" & LF &
     "            while (j < len && s[j] != '""')" & LF &
     "                j += (s[j] == '\\' && j + 1 < len) ? 2 : 1;" & LF &
     "            if (j < len)" & LF &
     "                j++;" & LF &
     "        } else if (c == '#') {                  /* a comment, as is */" & LF &
     "            while (j < len && s[j] != '\n')" & LF &
     "                j++;" & LF &
     "        } else if (c == '$' && (used == 0 || !lex_word_char(o[used - 1]))) {" & LF &
     "            const hbnf_sym *y;" & LF &
     "            size_t vl;" & LF &
     "            while (j < len && (isalnum((unsigned char)s[j]) || s[j] == '_'))" & LF &
     "                j++;" & LF &
     "            y = hbnf_symget(s + i + 1, j - i - 1);" & LF &
     "            if (!y) {" & LF &
     "                snprintf(msg, msglen, ""macro '%.*s' not defined""," & LF &
     "                         (int)(j - i - 1), s + i + 1);" & LF &
     "                free(o);" & LF &
     "                return NULL;" & LF &
     "            }" & LF &
     "            vl = strlen(y->val);" & LF &
     "            if (hbnf_nsegs < sizeof hbnf_segs / sizeof hbnf_segs[0]) {" & LF &
     "                hbnf_segs[hbnf_nsegs].line = line;" & LF &
     "                hbnf_segs[hbnf_nsegs].col0 = col;" & LF &
     "                hbnf_segs[hbnf_nsegs].col1 = col + vl;" & LF &
     "                hbnf_segs[hbnf_nsegs].sym = y;" & LF &
     "                hbnf_nsegs++;" & LF &
     "            }" & LF &
     "            hbnf_put(&o, &used, &cap, y->val, vl);" & LF &
     "            col += vl;" & LF &
     "            i = j;" & LF &
     "            continue;" & LF &
     "        }" & LF &
     "        hbnf_put(&o, &used, &cap, s + i, j - i);" & LF &
     "        for (; i < j; i++) {" & LF &
     "            if (s[i] == '\n') {" & LF &
     "                line++;" & LF &
     "                col = 1;" & LF &
     "            } else {" & LF &
     "                col++;" & LF &
     "            }" & LF &
     "        }" & LF &
     "    }" & LF &
     "    o[used] = '\0';" & LF &
     "    return o;" & LF &
     "}" & LF &
     "" & LF &
     "/* On an error in or after an expanded value on the error's line, say" & LF &
     "   where the value came from: the one the error is in, else the last one" & LF &
     "   before it. */" & LF &
     "static void hbnf_trail(char *msg, size_t msglen, size_t line, size_t col) {" & LF &
     "    size_t k, used = strlen(msg);" & LF &
     "    const hbnf_seg *g = NULL;" & LF &
     "" & LF &
     "    for (k = 0; k < hbnf_nsegs; k++) {" & LF &
     "        if (hbnf_segs[k].line != line || col < hbnf_segs[k].col0)" & LF &
     "            continue;" & LF &
     "        g = &hbnf_segs[k];" & LF &
     "        if (col < g->col1)" & LF &
     "            break;" & LF &
     "    }" & LF &
     "    if (g) {" & LF &
     "        if (!g->sym->line)" & LF &
     "            snprintf(msg + used, msglen - used," & LF &
     "                     ""\n  ($%s = \""%s\"", from the command line)""," & LF &
     "                     g->sym->nam, g->sym->val);" & LF &
     "        else if (g->sym->file)" & LF &
     "            snprintf(msg + used, msglen - used," & LF &
     "                     ""\n  ($%s = \""%s\"", defined at %s:%zu)""," & LF &
     "                     g->sym->nam, g->sym->val, g->sym->file, g->sym->line);" & LF &
     "        else" & LF &
     "            snprintf(msg + used, msglen - used," & LF &
     "                     ""\n  ($%s = \""%s\"", defined at line %zu)""," & LF &
     "                     g->sym->nam, g->sym->val, g->sym->line);" & LF &
     "    }" & LF &
     "}" & LF &
     "" & LF &
     "/* The end of a parse: the config's own macros go, -D ones stay. */" & LF &
     "static void hbnf_macros_done(void) {" & LF &
     "    hbnf_sym **pp = &hbnf_syms, *y;" & LF &
     "" & LF &
     "    while ((y = *pp) != NULL) {" & LF &
     "        if (y->persist) {" & LF &
     "            pp = &y->next;" & LF &
     "        } else {" & LF &
     "            *pp = y->next;" & LF &
     "            hbnf_sym_free(y);" & LF &
     "        }" & LF &
     "    }" & LF &
     "}";

   C_No_Macros : constant String :=
     "/* No `macros` directive: a statement is lexed as it is written. */" & LF &
     "static char *hbnf_expand(const char *s, size_t len, char *msg, size_t msglen) {" & LF &
     "    char *o = (char *)malloc(len + 1);" & LF &
     "" & LF &
     "    (void)msg;" & LF &
     "    (void)msglen;" & LF &
     "    if (!o)" & LF &
     "        hbnf_oom();" & LF &
     "    memcpy(o, s, len);" & LF &
     "    o[len] = '\0';" & LF &
     "    return o;" & LF &
     "}" & LF &
     "" & LF &
     "static void hbnf_trail(char *msg, size_t msglen, size_t line, size_t col) {" & LF &
     "    (void)msg;" & LF &
     "    (void)msglen;" & LF &
     "    (void)line;" & LF &
     "    (void)col;" & LF &
     "}" & LF &
     "" & LF &
     "static void hbnf_define(const token_t *toks, size_t n, size_t line) {" & LF &
     "    (void)toks;" & LF &
     "    (void)n;" & LF &
     "    (void)line;" & LF &
     "}" & LF &
     "" & LF &
     "static void hbnf_macros_done(void) {" & LF &
     "}";

   Rust_Lexer : constant String :=
     "fn lx_digit(c: u8) -> bool { c.is_ascii_digit() }" & LF &
     "fn lx_word_start(c: u8) -> bool { c.is_ascii_alphabetic() || c == b'_' || c == b'-' }" & LF &
     "fn lx_word_char(c: u8) -> bool { lx_word_start(c) || lx_digit(c) || c == b'.' }" & LF &
     "" & LF &
     "pub fn lex(text: &str) -> Vec<Token> {" & LF &
     "    let b = text.as_bytes();" & LF &
     "    let mut toks = Vec::new();" & LF &
     "    let mut i = 0usize; let mut line = 1usize; let mut col = 1usize;" & LF &
     "    while i < b.len() {" & LF &
     "        let c = b[i];" & LF &
     "        // Hand-written jet scanners (schema `{ }` blocks) win first." & LF &
     "        let (jl, jk) = jet_dispatch(b, i, b.len());" & LF &
     "        if jl > 0 {" & LF &
     "            toks.push(Token { kind: jk, text: text[i..i + jl].to_string(), line, col });" & LF &
     "            i += jl; col += jl;" & LF &
     "            continue;" & LF &
     "        }" & LF &
     "        if c == b' ' || c == b'\t' || c == b'\r' { i += 1; col += 1; }" & LF &
     "        else if c == b'\n' { i += 1; line += 1; col = 1; }" & LF &
     "        // backslash-newline continues the line, as parse.y's lgetc()" & LF &
     "        else if c == b'\\' && i + 1 < b.len() && b[i + 1] == b'\n' { i += 2; line += 1; col = 1; }" & LF &
     "        else if c == b'#' { while i < b.len() && b[i] != b'\n' { i += 1; } }" & LF &
     "        else if c == b'""' {" & LF &
     "            let sc = col; let sl = line; let mut s = String::new();" & LF &
     "            i += 1; col += 1;" & LF &
     "            while i < b.len() && b[i] != b'""' {" & LF &
     "                // inside quotes parse.y drops backslash-newline and a bare newline" & LF &
     "                if b[i] == b'\\' && i + 1 < b.len() && b[i + 1] == b'\n' { i += 2; line += 1; col = 1; continue; }" & LF &
     "                if b[i] == b'\n' { i += 1; line += 1; col = 1; continue; }" & LF &
     "                if b[i] == b'\\' && i + 1 < b.len() { i += 1; col += 1; }" & LF &
     "                s.push(b[i] as char); i += 1; col += 1;" & LF &
     "            }" & LF &
     "            if i < b.len() && b[i] == b'""' { i += 1; col += 1; }" & LF &
     "            toks.push(Token { kind: Kind::Str, text: s, line: sl, col: sc });" & LF &
     "        }" & LF &
     "        else if lx_digit(c) || (c == b'-' && i + 1 < b.len() && lx_digit(b[i + 1])) {" & LF &
     "            // -N is a number too, as in parse.y's lexers" & LF &
     "            let s = i; let sc = col;" & LF &
     "            if c == b'-' { i += 1; col += 1; }" & LF &
     "            while i < b.len() && lx_digit(b[i]) { i += 1; col += 1; }" & LF &
     "            if i < b.len() && lx_word_char(b[i]) {" & LF &
     "                // dotted/alphanumeric run (1.2.3.4, 123abc) is one word" & LF &
     "                i = s; col = sc;" & LF &
     "                while i < b.len() && lx_word_char(b[i]) { i += 1; col += 1; }" & LF &
     "                toks.push(Token { kind: Kind::Atom, text: text[s..i].to_string(), line, col: sc });" & LF &
     "            } else {" & LF &
     "                toks.push(Token { kind: Kind::Int, text: text[s..i].to_string(), line, col: sc });" & LF &
     "            }" & LF &
     "        }" & LF &
     "        else if lx_word_start(c) {" & LF &
     "            let s = i; let sc = col;" & LF &
     "            while i < b.len() && lx_word_char(b[i]) { i += 1; col += 1; }" & LF &
     "            toks.push(Token { kind: Kind::Atom, text: text[s..i].to_string(), line, col: sc });" & LF &
     "        }" & LF &
     "        else {" & LF &
     "            toks.push(Token { kind: Kind::Punct, text: (c as char).to_string(), line, col });" & LF &
     "            i += 1; col += 1;" & LF &
     "        }" & LF &
     "    }" & LF &
     "    toks.push(Token { kind: Kind::Eof, text: String::new(), line, col });" & LF &
     "    toks" & LF &
     "}" & LF &
     "" & LF &
     "pub fn parse_text(text: &str) -> Result<@ROOT_TYPE@, ParseError> {" & LF &
     "    let toks = lex(text);" & LF &
     "    let lines: Vec<&str> = text.split('\n').collect();" & LF &
     "    parse_tokens(&toks, &lines)" & LF &
     "}";

   Zig_Lexer : constant String :=
     "fn lxDigit(c: u8) bool { return c >= '0' and c <= '9'; }" & LF &
     "fn lxWordStart(c: u8) bool {" & LF &
     "    return (c >= 'a' and c <= 'z') or (c >= 'A' and c <= 'Z')" & LF &
     "        or c == '_' or c == '-';" & LF &
     "}" & LF &
     "fn lxWordChar(c: u8) bool { return lxWordStart(c) or lxDigit(c) or c == '.'; }" & LF &
     "" & LF &
     "pub fn lex(alloc: std.mem.Allocator, text: []const u8) ![]Token {" & LF &
     "    var toks = std.ArrayList(Token).empty;" & LF &
     "    var i: usize = 0; var line: usize = 1; var col: usize = 1;" & LF &
     "    while (i < text.len) {" & LF &
     "        const c = text[i];" & LF &
     "        {" & LF &
     "            // Hand-written jet scanners (schema `{ }` blocks) win first." & LF &
     "            var jk: Kind = .eof;" & LF &
     "            const jl = jet_dispatch(text, i, text.len, &jk);" & LF &
     "            if (jl > 0) {" & LF &
     "                try toks.append(alloc, .{ .kind = jk, .text = text[i..i + jl], .line = line, .col = col });" & LF &
     "                i += jl; col += jl;" & LF &
     "                continue;" & LF &
     "            }" & LF &
     "        }" & LF &
     "        if (c == ' ' or c == '\t' or c == '\r') { i += 1; col += 1; }" & LF &
     "        else if (c == '\n') { i += 1; line += 1; col = 1; }" & LF &
     "        // backslash-newline continues the line, as parse.y's lgetc()" & LF &
     "        else if (c == '\\' and i + 1 < text.len and text[i + 1] == '\n') { i += 2; line += 1; col = 1; }" & LF &
     "        else if (c == '#') { while (i < text.len and text[i] != '\n') i += 1; }" & LF &
     "        else if (c == '""') {" & LF &
     "            const sc = col;" & LF &
     "            const sl = line;" & LF &
     "            var s = std.ArrayList(u8).empty;" & LF &
     "            i += 1; col += 1;" & LF &
     "            while (i < text.len and text[i] != '""') {" & LF &
     "                // inside quotes parse.y drops backslash-newline and a bare newline" & LF &
     "                if (text[i] == '\\' and i + 1 < text.len and text[i + 1] == '\n') { i += 2; line += 1; col = 1; continue; }" & LF &
     "                if (text[i] == '\n') { i += 1; line += 1; col = 1; continue; }" & LF &
     "                if (text[i] == '\\' and i + 1 < text.len) { i += 1; col += 1; }" & LF &
     "                try s.append(alloc, text[i]);" & LF &
     "                i += 1; col += 1;" & LF &
     "            }" & LF &
     "            if (i < text.len and text[i] == '""') { i += 1; col += 1; }" & LF &
     "            try toks.append(alloc, .{ .kind = .str, .text = try s.toOwnedSlice(alloc), .line = sl, .col = sc });" & LF &
     "        }" & LF &
     "        else if (lxDigit(c) or (c == '-' and i + 1 < text.len and lxDigit(text[i + 1]))) {" & LF &
     "            // -N is a number too, as in parse.y's lexers" & LF &
     "            const s = i; const sc = col;" & LF &
     "            if (c == '-') { i += 1; col += 1; }" & LF &
     "            while (i < text.len and lxDigit(text[i])) { i += 1; col += 1; }" & LF &
     "            if (i < text.len and lxWordChar(text[i])) {" & LF &
     "                // dotted/alphanumeric run (1.2.3.4, 123abc) is one word" & LF &
     "                i = s; col = sc;" & LF &
     "                while (i < text.len and lxWordChar(text[i])) { i += 1; col += 1; }" & LF &
     "                try toks.append(alloc, .{ .kind = .atom, .text = text[s..i], .line = line, .col = sc });" & LF &
     "            } else {" & LF &
     "                try toks.append(alloc, .{ .kind = .int, .text = text[s..i], .line = line, .col = sc });" & LF &
     "            }" & LF &
     "        }" & LF &
     "        else if (lxWordStart(c)) {" & LF &
     "            const s = i; const sc = col;" & LF &
     "            while (i < text.len and lxWordChar(text[i])) { i += 1; col += 1; }" & LF &
     "            try toks.append(alloc, .{ .kind = .atom, .text = text[s..i], .line = line, .col = sc });" & LF &
     "        }" & LF &
     "        else {" & LF &
     "            try toks.append(alloc, .{ .kind = .punct, .text = text[i..i + 1], .line = line, .col = col });" & LF &
     "            i += 1; col += 1;" & LF &
     "        }" & LF &
     "    }" & LF &
     "    try toks.append(alloc, .{ .kind = .eof, .text = """", .line = line, .col = col });" & LF &
     "    return toks.toOwnedSlice(alloc);" & LF &
     "}" & LF &
     "" & LF &
     "pub fn parse_text(alloc: std.mem.Allocator, text: []const u8," & LF &
     "                  err: *[512]u8, err_line: *usize, err_col: *usize) ParseError!@ROOT_TYPE@ {" & LF &
     "    const toks = try lex(alloc, text);" & LF &
     "    var lines = std.ArrayList([]const u8).empty;" & LF &
     "    var s: usize = 0;" & LF &
     "    for (text, 0..) |ch, idx| {" & LF &
     "        if (ch == '\n') {" & LF &
     "            try lines.append(alloc, text[s..idx]);" & LF &
     "            s = idx + 1;" & LF &
     "        }" & LF &
     "    }" & LF &
     "    try lines.append(alloc, text[s..]);" & LF &
     "    return parse_tokens(alloc, toks, lines.items, err, err_line, err_col);" & LF &
     "}";

   Ada_Lexer : constant String :=
     "   function Lex (Text : String) return Token_Vectors.Vector is" & LF &
     "      Toks : Token_Vectors.Vector;" & LF &
     "      I    : Natural := Text'First;" & LF &
     "      Line : Natural := 1;" & LF &
     "      Col  : Natural := 1;" & LF &
     "      C    : Character;" & LF &
     "   begin" & LF &
     "      while I <= Text'Last loop" & LF &
     "         C := Text (I);" & LF &
     "         declare" & LF &
     "            JK : Token_Kind;" & LF &
     "            JL : constant Natural := Jet_Dispatch (Text, I, Text'Last, JK);" & LF &
     "         begin" & LF &
     "            if JL > 0 then" & LF &
     "               Toks.Append (Token'(JK, To_Unbounded_String (Text (I .. I + JL - 1)), Line, Col));" & LF &
     "               I := I + JL; Col := Col + JL;" & LF &
     "            elsif C = ' ' or else C = ASCII.HT or else C = ASCII.CR then" & LF &
     "               I := I + 1; Col := Col + 1;" & LF &
     "         elsif C = ASCII.LF then" & LF &
     "            I := I + 1; Line := Line + 1; Col := 1;" & LF &
     "         --  backslash-newline continues the line, as parse.y's lgetc()" & LF &
     "         elsif C = '\' and then I < Text'Last and then Text (I + 1) = ASCII.LF then" & LF &
     "            I := I + 2; Line := Line + 1; Col := 1;" & LF &
     "         elsif C = '#' then" & LF &
     "            while I <= Text'Last and then Text (I) /= ASCII.LF loop" & LF &
     "               I := I + 1;" & LF &
     "            end loop;" & LF &
     "         elsif C = '""' then" & LF &
     "            declare" & LF &
     "               SC  : constant Natural := Col;" & LF &
     "               SL  : constant Natural := Line;" & LF &
     "               Buf : Unbounded_String;" & LF &
     "            begin" & LF &
     "               I := I + 1; Col := Col + 1;" & LF &
     "               while I <= Text'Last and then Text (I) /= '""' loop" & LF &
     "                  --  inside quotes parse.y drops backslash-newline and a" & LF &
     "                  --  bare newline, counting the line" & LF &
     "                  if Text (I) = '\' and then I < Text'Last" & LF &
     "                    and then Text (I + 1) = ASCII.LF" & LF &
     "                  then" & LF &
     "                     I := I + 2; Line := Line + 1; Col := 1;" & LF &
     "                  elsif Text (I) = ASCII.LF then" & LF &
     "                     I := I + 1; Line := Line + 1; Col := 1;" & LF &
     "                  else" & LF &
     "                     if Text (I) = '\' and then I < Text'Last then" & LF &
     "                        I := I + 1; Col := Col + 1;" & LF &
     "                     end if;" & LF &
     "                     Append (Buf, Text (I));" & LF &
     "                     I := I + 1; Col := Col + 1;" & LF &
     "                  end if;" & LF &
     "               end loop;" & LF &
     "               if I <= Text'Last then" & LF &
     "                  I := I + 1; Col := Col + 1;" & LF &
     "               end if;" & LF &
     "               Toks.Append (Token'(Str, Buf, SL, SC));" & LF &
     "            end;" & LF &
     "         elsif C in '0' .. '9'" & LF &
     "           or else (C = '-' and then I < Text'Last" & LF &
     "                    and then Text (I + 1) in '0' .. '9')" & LF &
     "         then" & LF &
     "            --  -N is a number too, as in parse.y's lexers" & LF &
     "            declare" & LF &
     "               SC      : constant Natural := Col;" & LF &
     "               Start_I : constant Natural := I;" & LF &
     "               Buf     : Unbounded_String;" & LF &
     "            begin" & LF &
     "               if C = '-' then" & LF &
     "                  Append (Buf, C); I := I + 1; Col := Col + 1;" & LF &
     "               end if;" & LF &
     "               while I <= Text'Last and then Text (I) in '0' .. '9' loop" & LF &
     "                  Append (Buf, Text (I)); I := I + 1; Col := Col + 1;" & LF &
     "               end loop;" & LF &
     "               if I <= Text'Last" & LF &
     "                 and then (Text (I) in 'a' .. 'z' or else Text (I) in 'A' .. 'Z'" & LF &
     "                   or else Text (I) = '.' or else Text (I) = '_'" & LF &
     "                   or else Text (I) = '-')" & LF &
     "               then" & LF &
     "                  --  dotted/alphanumeric run (1.2.3.4, 123abc) is one word" & LF &
     "                  I := Start_I; Col := SC;" & LF &
     "                  Buf := Null_Unbounded_String;" & LF &
     "                  while I <= Text'Last loop" & LF &
     "                     C := Text (I);" & LF &
     "                     exit when not (C in 'a' .. 'z' or else C in 'A' .. 'Z'" & LF &
     "                       or else C in '0' .. '9' or else C = '_' or else C = '-'" & LF &
     "                       or else C = '.');" & LF &
     "                     Append (Buf, C); I := I + 1; Col := Col + 1;" & LF &
     "                  end loop;" & LF &
     "                  Toks.Append (Token'(Atom, Buf, Line, SC));" & LF &
     "               else" & LF &
     "                  Toks.Append (Token'(Int, Buf, Line, SC));" & LF &
     "               end if;" & LF &
     "            end;" & LF &
     "         elsif C in 'a' .. 'z' or else C in 'A' .. 'Z' or else C = '_' or else C = '-' then" & LF &
     "            declare" & LF &
     "               SC  : constant Natural := Col;" & LF &
     "               Buf : Unbounded_String;" & LF &
     "            begin" & LF &
     "               while I <= Text'Last loop" & LF &
     "                  C := Text (I);" & LF &
     "                  exit when not (C in 'a' .. 'z' or else C in 'A' .. 'Z'" & LF &
     "                    or else C in '0' .. '9' or else C = '_' or else C = '-'" & LF &
     "                    or else C = '.');" & LF &
     "                  Append (Buf, C); I := I + 1; Col := Col + 1;" & LF &
     "               end loop;" & LF &
     "               Toks.Append (Token'(Atom, Buf, Line, SC));" & LF &
     "            end;" & LF &
     "         else" & LF &
     "            declare" & LF &
     "               Buf : Unbounded_String;" & LF &
     "            begin" & LF &
     "               Append (Buf, C);" & LF &
     "               Toks.Append (Token'(Punct, Buf, Line, Col));" & LF &
     "               I := I + 1; Col := Col + 1;" & LF &
     "            end;" & LF &
     "         end if;" & LF &
     "         end;" & LF &
     "      end loop;" & LF &
     "      Toks.Append (Token'(Eof, Null_Unbounded_String, Line, Col));" & LF &
     "      return Toks;" & LF &
     "   end Lex;" & LF &
     "" & LF &
     "   function Parse_Text (Text : String) return @ROOT_TYPE@ is" & LF &
     "      Toks  : Token_Vectors.Vector := Lex (Text);" & LF &
     "      Lines : Line_Vectors.Vector;" & LF &
     "      S     : Natural := Text'First;" & LF &
     "   begin" & LF &
     "      for K in Text'Range loop" & LF &
     "         if Text (K) = ASCII.LF then" & LF &
     "            Lines.Append (To_Unbounded_String (Text (S .. K - 1)));" & LF &
     "            S := K + 1;" & LF &
     "         end if;" & LF &
     "      end loop;" & LF &
     "      Lines.Append (To_Unbounded_String (Text (S .. Text'Last)));" & LF &
     "      declare" & LF &
     "         P : Parser := (Toks => Toks, Lines => Lines, Pos => 1);" & LF &
     "         R : @ROOT_TYPE@;" & LF &
     "      begin" & LF &
     "         R := @ROOT_FN@ (P);" & LF &
     "         if P.Pos <= Natural (P.Toks.Length) and then P.Toks (P.Pos).Kind /= Eof then" & LF &
     "            Fail (P, ""end of config"");" & LF &
     "         end if;" & LF &
     "         return R;" & LF &
     "      end;" & LF &
     "   end Parse_Text;";

   Conf_H : constant String :=
     "/* The configuration tree root, populated by parse_config(). */" & LF &
     "extern @ROOT_TYPE@ *conf;" & LF &
     "" & LF &
     "/* yyerror-style error handler: called by the parser at the point of failure" & LF &
     "   with the caret message and its 1-based line.  The default handler prints" & LF &
     "   ""file:line: msg"" (file taken from conf_file) and exit(1)s; override" & LF &
     "   conf_error to take the message yourself, in which case parse_config returns" & LF &
     "   -1 after the handler. */" & LF &
     "typedef void (*conf_error_fn)(size_t line, const char *msg);" & LF &
     "extern conf_error_fn conf_error;" & LF &
     "" & LF &
     "/* Filename being parsed: set by parse_config, used by the default handler. */" & LF &
     "extern const char *conf_file;" & LF &
     "" & LF &
     "/* Read filename, populate the global `conf`.  Returns 0 on success, -1 on" & LF &
     "   error (after conf_error has been called). */" & LF &
     "int parse_config(const char *filename);" & LF &
     "" & LF &
     "/* Return the current config root (NULL before a successful parse_config)." & LF &
     "   Convenience for FFI languages that cannot read the `conf` global. */" & LF &
     "@ROOT_TYPE@ *conf_ptr(void);" & LF &
     "" & LF &
     "/* Free the current config tree and reset the root (the SIGHUP reload" & LF &
     "   path).  Safe to call when conf is NULL. */" & LF &
     "void free_conf(void);";

   Conf_Tail_C : constant String :=
     "@ROOT_TYPE@ *conf = NULL;" & LF &
     "const char *conf_file = NULL;" & LF &
     "" & LF &
     "/* Default handler: print ""file:line: <caret message>"" and exit(1).  Override" & LF &
     "   conf_error with your own to take the message elsewhere (then parse_config" & LF &
     "   returns -1 after the handler). */" & LF &
     "static void conf_error_default(size_t line, const char *msg) {" & LF &
     "    if (conf_file) {" & LF &
     "        if (line)" & LF &
     "            fprintf(stderr, ""%s:%zu: %s\n"", conf_file, line, msg);" & LF &
     "        else" & LF &
     "            fprintf(stderr, ""%s: %s\n"", conf_file, msg);" & LF &
     "    } else {" & LF &
     "        if (line)" & LF &
     "            fprintf(stderr, ""%zu: %s\n"", line, msg);" & LF &
     "        else" & LF &
     "            fprintf(stderr, ""%s\n"", msg);" & LF &
     "    }" & LF &
     "    exit(1);" & LF &
     "}" & LF &
     "conf_error_fn conf_error = conf_error_default;" & LF &
     "" & LF &
     "int parse_config(const char *filename) {" & LF &
     "    FILE *f = fopen(filename, ""r"");" & LF &
     "    char *buf;" & LF &
     "    long len;" & LF &
     "    char err[512];" & LF &
     "    size_t line = 0, col = 0;" & LF &
     "" & LF &
     "    if (!f) {" & LF &
     "        conf_error(0, ""cannot open file"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    if (fseek(f, 0, SEEK_END) != 0 || (len = ftell(f)) < 0 ||" & LF &
     "        fseek(f, 0, SEEK_SET) != 0) {" & LF &
     "        fclose(f);" & LF &
     "        conf_error(0, ""cannot read file"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    buf = (char *)malloc((size_t)len + 1);" & LF &
     "    if (!buf) {" & LF &
     "        fclose(f);" & LF &
     "        conf_error(0, ""out of memory"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    if (len > 0 && fread(buf, 1, (size_t)len, f) != (size_t)len) {" & LF &
     "        free(buf);" & LF &
     "        fclose(f);" & LF &
     "        conf_error(0, ""read error"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    buf[len] = '\0';" & LF &
     "    fclose(f);" & LF &
     "" & LF &
     "    conf_file = filename;" & LF &
     "    conf = (@ROOT_TYPE@ *)calloc(1, sizeof *conf);" & LF &
     "    if (!conf) {" & LF &
     "        free(buf);" & LF &
     "        conf_error(0, ""out of memory"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    if (!parse_text(buf, conf, err, sizeof err, &line, &col)) {" & LF &
     "        conf_error(line, err);" & LF &
     "        free(buf);" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    free(buf);" & LF &
     "    return 0;" & LF &
     "}" & LF &
     "" & LF &
     "@ROOT_TYPE@ *conf_ptr(void) { return conf; }";

   Conf_Tail_C_Stmt : constant String :=
     "@ROOT_TYPE@ *conf = NULL;" & LF &
     "const char *conf_file = NULL;" & LF &
     "" & LF &
     "/* Default handler: print ""file:line: <caret message>"" and exit(1).  Override" & LF &
     "   conf_error with your own to take the message elsewhere (then parse_config" & LF &
     "   returns -1 after the handler). */" & LF &
     "static void conf_error_default(size_t line, const char *msg) {" & LF &
     "    if (conf_file) {" & LF &
     "        if (line)" & LF &
     "            fprintf(stderr, ""%s:%zu: %s\n"", conf_file, line, msg);" & LF &
     "        else" & LF &
     "            fprintf(stderr, ""%s: %s\n"", conf_file, msg);" & LF &
     "    } else {" & LF &
     "        if (line)" & LF &
     "            fprintf(stderr, ""%zu: %s\n"", line, msg);" & LF &
     "        else" & LF &
     "            fprintf(stderr, ""%s\n"", msg);" & LF &
     "    }" & LF &
     "    exit(1);" & LF &
     "}" & LF &
     "conf_error_fn conf_error = conf_error_default;" & LF &
     "" & LF &
     "/* The file is read a block at a time and parsed one statement at a time" & LF &
     "   (parse_file); the tree is kept. */" & LF &
     "int parse_config(const char *filename) {" & LF &
     "    char err[512];" & LF &
     "    size_t line = 0, col = 0;" & LF &
     "" & LF &
     "    conf_file = filename;" & LF &
     "    conf = (@ROOT_TYPE@ *)calloc(1, sizeof *conf);" & LF &
     "    if (!conf) {" & LF &
     "        conf_error(0, ""out of memory"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    if (!parse_file(filename, conf, err, sizeof err, &line, &col)) {" & LF &
     "        conf_error(line, err);" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    return 0;" & LF &
     "}" & LF &
     "" & LF &
     "@ROOT_TYPE@ *conf_ptr(void) { return conf; }";

   Conf_H_Typed : constant String :=
     "/* The daemon's own conf tree, filled by parse_config(); the action jets" & LF &
     "   build it into the caller's struct.  The `conf` global is the daemon's" & LF &
     "   (declared in its header, included by the grammar's preamble). */" & LF &
     "int parse_config(const char *filename, @CONF_TYPE@ *conf);" & LF &
     "" & LF &
     "/* yyerror-style error handler: called with each error's message and its" & LF &
     "   1-based line (a syntax error, or every error an action jet reports).  The" & LF &
     "   default handler prints ""file:line: msg"" (file taken from conf_file) to" & LF &
     "   stderr and returns, as parse.y's yyerror does; parse_config then returns" & LF &
     "   -1 and the daemon decides (exit at startup, keep the running config on a" & LF &
     "   reload).  Override conf_error to take the messages yourself. */" & LF &
     "typedef void (*conf_error_fn)(size_t line, const char *msg);" & LF &
     "extern conf_error_fn conf_error;" & LF &
     "" & LF &
     "/* Filename being parsed: set by parse_config, used by the default handler. */" & LF &
     "extern const char *conf_file;";

   Conf_Tail_C_Typed : constant String :=
     "const char *conf_file = NULL;" & LF &
     "" & LF &
     "/* Default handler: print ""file:line: <message>"" to stderr and return, as" & LF &
     "   parse.y's yyerror does; parse_config returns -1 once the parse is over." & LF &
     "   Override conf_error with your own to take the messages elsewhere. */" & LF &
     "static void conf_error_default(size_t line, const char *msg) {" & LF &
     "    if (conf_file) {" & LF &
     "        if (line)" & LF &
     "            fprintf(stderr, ""%s:%zu: %s\n"", conf_file, line, msg);" & LF &
     "        else" & LF &
     "            fprintf(stderr, ""%s: %s\n"", conf_file, msg);" & LF &
     "    } else {" & LF &
     "        if (line)" & LF &
     "            fprintf(stderr, ""%zu: %s\n"", line, msg);" & LF &
     "        else" & LF &
     "            fprintf(stderr, ""%s\n"", msg);" & LF &
     "    }" & LF &
     "}" & LF &
     "conf_error_fn conf_error = conf_error_default;" & LF &
     "" & LF &
     "/* The grammar's epilogue defines conf_init() to reset the conf's list heads" & LF &
     "   (the action jets append to them, so they must be TAILQ_INIT'd first)." & LF &
     "   The parse tree is only the action jets' input: it is freed, with the" & LF &
     "   string arena, before parse_config returns, so a jet copies whatever it" & LF &
     "   keeps. */" & LF &
     "int parse_config(const char *filename, @CONF_TYPE@ *xconf) {" & LF &
     "    FILE *f = fopen(filename, ""r"");" & LF &
     "    char *buf;" & LF &
     "    long len;" & LF &
     "    char err[512];" & LF &
     "    size_t line = 0, col = 0;" & LF &
     "" & LF &
     "    if (!f) {" & LF &
     "        conf_error(0, ""cannot open file"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    if (fseek(f, 0, SEEK_END) != 0 || (len = ftell(f)) < 0 ||" & LF &
     "        fseek(f, 0, SEEK_SET) != 0) {" & LF &
     "        fclose(f);" & LF &
     "        conf_error(0, ""cannot read file"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    buf = (char *)malloc((size_t)len + 1);" & LF &
     "    if (!buf) {" & LF &
     "        fclose(f);" & LF &
     "        conf_error(0, ""out of memory"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    if (len > 0 && fread(buf, 1, (size_t)len, f) != (size_t)len) {" & LF &
     "        free(buf);" & LF &
     "        fclose(f);" & LF &
     "        conf_error(0, ""read error"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    buf[len] = '\0';" & LF &
     "    fclose(f);" & LF &
     "" & LF &
     "    conf_file = filename;" & LF &
     "    conf = xconf;" & LF &
     "    conf_init();" & LF &
     "    {" & LF &
     "        @ROOT_TYPE@ ast;" & LF &
     "        bool ok;" & LF &
     "        memset(&ast, 0, sizeof ast);" & LF &
     "        bind_errors = 0;" & LF &
     "        bind_report = conf_error;   /* every action error, as it happens */" & LF &
     "        ok = parse_text(buf, &ast, err, sizeof err, &line, &col);" & LF &
     "        bind_report = NULL;" & LF &
     "        free_@ROOT_C@(&ast);        /* the tree and the string arena */" & LF &
     "        free(buf);" & LF &
     "        if (!ok) {" & LF &
     "            if (!bind_errors)      /* a syntax error: not reported yet */" & LF &
     "                conf_error(line, err);" & LF &
     "            return -1;" & LF &
     "        }" & LF &
     "    }" & LF &
     "    return 0;" & LF &
     "}";

   Conf_Tail_C_Typed_Stmt : constant String :=
     "const char *conf_file = NULL;" & LF &
     "" & LF &
     "/* Default handler: print ""file:line: <message>"" to stderr and return, as" & LF &
     "   parse.y's yyerror does; parse_config returns -1 once the parse is over." & LF &
     "   Override conf_error with your own to take the messages elsewhere. */" & LF &
     "static void conf_error_default(size_t line, const char *msg) {" & LF &
     "    if (conf_file) {" & LF &
     "        if (line)" & LF &
     "            fprintf(stderr, ""%s:%zu: %s\n"", conf_file, line, msg);" & LF &
     "        else" & LF &
     "            fprintf(stderr, ""%s: %s\n"", conf_file, msg);" & LF &
     "    } else {" & LF &
     "        if (line)" & LF &
     "            fprintf(stderr, ""%zu: %s\n"", line, msg);" & LF &
     "        else" & LF &
     "            fprintf(stderr, ""%s\n"", msg);" & LF &
     "    }" & LF &
     "}" & LF &
     "conf_error_fn conf_error = conf_error_default;" & LF &
     "" & LF &
     "/* Every error, syntax or action, as it is found: conf_file names the" & LF &
     "   file it is in (an included file while that one is read). */" & LF &
     "static void conf_report(size_t line, const char *msg) {" & LF &
     "    const char *top = conf_file;" & LF &
     "" & LF &
     "    if (hbnf_file)" & LF &
     "        conf_file = hbnf_file;" & LF &
     "    conf_error(line, msg);" & LF &
     "    conf_file = top;" & LF &
     "}" & LF &
     "" & LF &
     "/* The grammar's epilogue defines conf_init() to reset the conf's list heads" & LF &
     "   (the action jets append to them, so they must be TAILQ_INIT'd first)." & LF &
     "   The file is read a block at a time and parsed one statement at a time:" & LF &
     "   each statement is parsed, bound and freed, with its strings, before the" & LF &
     "   next is read, so a jet copies whatever it keeps.  Every error is" & LF &
     "   reported as it is found and the parse goes on, as parse.y's does;" & LF &
     "   parse_config then returns -1. */" & LF &
     "int parse_config(const char *filename, @CONF_TYPE@ *xconf) {" & LF &
     "    FILE *f;" & LF &
     "    hbnf_src_t src;" & LF &
     "    char err[512];" & LF &
     "    size_t line = 0, col = 0;" & LF &
     "    bool ok;" & LF &
     "" & LF &
     "    conf_file = filename;" & LF &
     "    if (!(f = fopen(filename, ""r""))) {" & LF &
     "        conf_error(0, ""cannot open file"");" & LF &
     "        return -1;" & LF &
     "    }" & LF &
     "    conf = xconf;" & LF &
     "    conf_init();" & LF &
     "    bind_report = conf_report;" & LF &
     "    hbnf_report = conf_report;" & LF &
     "    hbnf_src_file(&src, f);" & LF &
     "    ok = hbnf_stmts(&src, NULL, err, sizeof err, &line, &col);" & LF &
     "    hbnf_src_done(&src);" & LF &
     "    hbnf_report = NULL;" & LF &
     "    bind_report = NULL;" & LF &
     "    fclose(f);" & LF &
     "    return ok ? 0 : -1;" & LF &
     "}";

   Conf_Rust : constant String :=
     "// yyerror-style error handling: the parser calls config_error() at the point" & LF &
     "// of failure with the caret message.  The default handler prints" & LF &
     "// ""file:line: msg"" (file from CONF_FILE) and exit(1)s; override with" & LF &
     "// set_config_error to take the message yourself, in which case parse_config" & LF &
     "// returns the Err instead of exiting." & LF &
     "static CONFIG_ERROR: std::sync::OnceLock<fn(usize, &str)> = std::sync::OnceLock::new();" & LF &
     "static CONF_FILE: std::sync::Mutex<String> = std::sync::Mutex::new(String::new());" & LF &
     "" & LF &
     "fn default_config_error(line: usize, msg: &str) {" & LF &
     "    let file = CONF_FILE.lock().unwrap();" & LF &
     "    if !file.is_empty() {" & LF &
     "        if line > 0 {" & LF &
     "            eprintln!(""{}:{}: {}"", file, line, msg);" & LF &
     "        } else {" & LF &
     "            eprintln!(""{}: {}"", file, msg);" & LF &
     "        }" & LF &
     "    } else if line > 0 {" & LF &
     "        eprintln!(""{}: {}"", line, msg);" & LF &
     "    } else {" & LF &
     "        eprintln!(""{}"", msg);" & LF &
     "    }" & LF &
     "    std::process::exit(1);" & LF &
     "}" & LF &
     "" & LF &
     "pub fn set_config_error(f: fn(usize, &str)) {" & LF &
     "    let _ = CONFIG_ERROR.set(f);" & LF &
     "}" & LF &
     "" & LF &
     "fn config_error(line: usize, msg: &str) {" & LF &
     "    CONFIG_ERROR.get().copied().unwrap_or(default_config_error)(line, msg);" & LF &
     "}" & LF &
     "" & LF &
     "pub fn parse_config(path: &str) -> Result<@ROOT_TYPE@, ParseError> {" & LF &
     "    *CONF_FILE.lock().unwrap() = path.to_string();" & LF &
     "    let text = match std::fs::read_to_string(path) {" & LF &
     "        Ok(t) => t," & LF &
     "        Err(e) => {" & LF &
     "            let m = format!(""cannot open file: {}"", e);" & LF &
     "            config_error(0, &m);" & LF &
     "            return Err(ParseError { line: 0, col: 0, msg: m });" & LF &
     "        }" & LF &
     "    };" & LF &
     "    match parse_text(&text) {" & LF &
     "        Ok(r) => Ok(r)," & LF &
     "        Err(e) => {" & LF &
     "            config_error(e.line, &e.msg);" & LF &
     "            Err(e)" & LF &
     "        }" & LF &
     "    }" & LF &
     "}";

   Conf_Zig : constant String :=
     "pub var conf_file: ?[]const u8 = null;" & LF &
     "" & LF &
     "// yyerror-style handler: the parser calls config_error() at the point of" & LF &
     "// failure with the caret message.  Default prints ""file:line: msg"" (file from" & LF &
     "// conf_file) and exits; assign config_error to take the message yourself, in" & LF &
     "// which case parse_config returns the error instead of exiting." & LF &
     "pub var config_error: *const fn(usize, []const u8) void = defaultConfigError;" & LF &
     "" & LF &
     "fn defaultConfigError(line: usize, msg: []const u8) void {" & LF &
     "    if (conf_file) |f| {" & LF &
     "        if (line > 0) {" & LF &
     "            std.debug.print(""{s}:{d}: {s}\n"", .{ f, line, msg });" & LF &
     "        } else {" & LF &
     "            std.debug.print(""{s}: {s}\n"", .{ f, msg });" & LF &
     "        }" & LF &
     "    } else if (line > 0) {" & LF &
     "        std.debug.print(""{d}: {s}\n"", .{ line, msg });" & LF &
     "    } else {" & LF &
     "        std.debug.print(""{s}\n"", .{msg});" & LF &
     "    }" & LF &
     "    std.process.exit(1);" & LF &
     "}" & LF &
     "" & LF &
     "pub fn parse_config(alloc: std.mem.Allocator, path: []const u8) ParseError!@ROOT_TYPE@ {" & LF &
     "    conf_file = path;" & LF &
     "    var threaded = std.Io.Threaded.init(alloc, .{});" & LF &
     "    const text = std.Io.Dir.cwd().readFileAlloc(" & LF &
     "        threaded.io(), path, alloc, .limited(1 << 20)) catch {" & LF &
     "        config_error(0, ""cannot open file"");" & LF &
     "        return error.Invalid;" & LF &
     "    };" & LF &
     "    var err: [512]u8 = undefined;" & LF &
     "    var el: usize = 0;" & LF &
     "    var ec: usize = 0;" & LF &
     "    return parse_text(alloc, text, &err, &el, &ec) catch |e| {" & LF &
     "        config_error(el, std.mem.sliceTo(&err, 0));" & LF &
     "        return e;" & LF &
     "    };" & LF &
     "}";

   Conf_Ada : constant String :=
     "   function Read_File (Filename : String) return String is" & LF &
     "      F   : Ada.Text_IO.File_Type;" & LF &
     "      Buf : Unbounded_String;" & LF &
     "   begin" & LF &
     "      Ada.Text_IO.Open (F, Ada.Text_IO.In_File, Filename);" & LF &
     "      while not Ada.Text_IO.End_Of_File (F) loop" & LF &
     "         Append (Buf, Ada.Text_IO.Get_Line (F));" & LF &
     "         if not Ada.Text_IO.End_Of_File (F) then" & LF &
     "            Append (Buf, ASCII.LF);" & LF &
     "         end if;" & LF &
     "      end loop;" & LF &
     "      Ada.Text_IO.Close (F);" & LF &
     "      return To_String (Buf);" & LF &
     "   end Read_File;" & LF &
     "" & LF &
     "   function Parse_Config (Filename : String) return @ROOT_TYPE@ is" & LF &
     "   begin" & LF &
     "      return Parse_Text (Read_File (Filename));" & LF &
     "   end Parse_Config;";

   --  Replace every occurrence of From in Text with To.
   function Substitute (Text, From, To : String) return String;

end Templates;
