pragma Ada_2022;

with Ada.Containers.Vectors;
with Ada.Strings.Unbounded;
with Ada.Text_IO;

--  Regenerate templates.ads from the fixed lexer templates (templates/*.tmpl,
--  plain text with @PLACEHOLDER@ markers).  Run from sources/hbnf/ and redirect
--  to templates.ads:
--
--    gnatmake tools/gen_templates.adb && ./gen_templates > templates.ads
--
--  Only `"` needs escaping (doubled) for Ada; backslashes are literal and
--  newlines become `& LF &` concatenations.
procedure Gen_Templates is

   use Ada.Strings.Unbounded;

   package String_Vectors is new Ada.Containers.Vectors (Positive, Unbounded_String);

   function Read_File (Path : String) return String is
      F   : Ada.Text_IO.File_Type;
      Buf : Unbounded_String;
   begin
      Ada.Text_IO.Open (F, Ada.Text_IO.In_File, Path);
      while not Ada.Text_IO.End_Of_File (F) loop
         Append (Buf, Ada.Text_IO.Get_Line (F));
         if not Ada.Text_IO.End_Of_File (F) then
            Append (Buf, ASCII.LF);
         end if;
      end loop;
      Ada.Text_IO.Close (F);
      return To_String (Buf);
   end Read_File;

   --  Split Content into lines; a trailing LF does not add an empty line.
   function Split (Content : String) return String_Vectors.Vector is
      V     : String_Vectors.Vector;
      Start : Natural := Content'First;
   begin
      if Content'Length = 0 then
         return V;
      end if;
      for I in Content'Range loop
         if Content (I) = ASCII.LF then
            V.Append (To_Unbounded_String (Content (Start .. I - 1)));
            Start := I + 1;
         end if;
      end loop;
      if Start <= Content'Last then
         V.Append (To_Unbounded_String (Content (Start .. Content'Last)));
      end if;
      return V;
   end Split;

   procedure Put_Line (S : String) is
   begin
      Ada.Text_IO.Put_Line (S);
   end Put_Line;

   procedure Emit_Constant (Name : String; Content : String) is
      Lines : constant String_Vectors.Vector := Split (Content);
      Last  : constant Natural := Natural (Lines.Length);
   begin
      Put_Line ("   " & Name & " : constant String :=");
      for I in 1 .. Last loop
         declare
            Buf : Unbounded_String;
         begin
            for C of To_String (Lines (I)) loop
               Append (Buf, C);
               if C = '"' then
                  Append (Buf, '"');
               end if;
            end loop;
            if I < Last then
               Put_Line ("     """ & To_String (Buf) & """ & LF &");
            else
               Put_Line ("     """ & To_String (Buf) & """;");
            end if;
         end;
      end loop;
   end Emit_Constant;

begin
   Put_Line ("pragma Ada_2022;");
   Put_Line ("");
   Put_Line ("--  Generated by tools/gen_templates -- do not edit by hand.");
   Put_Line ("--  The fixed, schema-independent code-generator templates, held as");
   Put_Line ("--  string constants so the emitters never hand-escape another language.");
   Put_Line ("package Templates is");
   Put_Line ("");
   Put_Line ("   LF : constant Character := ASCII.LF;");
   Put_Line ("");
   Emit_Constant ("C_Lexer", Read_File ("templates/lexer.c"));
   Put_Line ("");
   Emit_Constant ("C_Parse_Text", Read_File ("templates/parse_text.c"));
   Put_Line ("");
   Emit_Constant ("C_Statements", Read_File ("templates/statements.c"));
   Put_Line ("");
   Emit_Constant ("C_Stmt_Text", Read_File ("templates/stmt_text.c"));
   Put_Line ("");
   Emit_Constant ("C_Macros", Read_File ("templates/macros.c"));
   Put_Line ("");
   Emit_Constant ("C_No_Macros", Read_File ("templates/nomacros.c"));
   Put_Line ("");
   Emit_Constant ("Rust_Lexer", Read_File ("templates/lexer.rs"));
   Put_Line ("");
   Emit_Constant ("Zig_Lexer", Read_File ("templates/lexer.zig"));
   Put_Line ("");
   Emit_Constant ("Ada_Lexer", Read_File ("templates/lexer.ada"));
   Put_Line ("");
   Emit_Constant ("Conf_H", Read_File ("templates/conf.h"));
   Put_Line ("");
   Emit_Constant ("Conf_Tail_C", Read_File ("templates/conf_tail.c"));
   Put_Line ("");
   Emit_Constant ("Conf_H_Typed", Read_File ("templates/conf_typed.h"));
   Put_Line ("");
   Emit_Constant ("Conf_Tail_C_Typed", Read_File ("templates/conf_tail_typed.c"));
   Put_Line ("");
   Emit_Constant ("Conf_Tail_C_Typed_Stmt",
                  Read_File ("templates/conf_tail_typed_stmt.c"));
   Put_Line ("");
   Emit_Constant ("Conf_Rust", Read_File ("templates/conf.rs"));
   Put_Line ("");
   Emit_Constant ("Conf_Zig", Read_File ("templates/conf.zig"));
   Put_Line ("");
   Emit_Constant ("Conf_Ada", Read_File ("templates/conf.ada"));
   Put_Line ("");
   Put_Line ("   --  Replace every occurrence of From in Text with To.");
   Put_Line ("   function Substitute (Text, From, To : String) return String;");
   Put_Line ("");
   Put_Line ("end Templates;");
end Gen_Templates;
