pragma Ada_2022;

with Ada.Containers.Vectors;
with Ada.Strings.Unbounded;
with Ada.Text_IO;

--  Regenerate templates.ads from the fixed lexer templates (templates/*.tmpl,
--  plain text with @PLACEHOLDER@ markers).  Run from sources/hbnf/ and redirect
--  to templates.ads:
--
--    gnatmake tools/gen_templates.adb && ./gen_templates > templates.ads
--
--  Only `"` needs escaping (doubled) for Ada; backslashes are literal and
--  newlines become `& LF &` concatenations.
procedure Gen_Templates is

   use Ada.Strings.Unbounded;

   package String_Vectors is new Ada.Containers.Vectors (Positive, Unbounded_String);

   function Read_File (Path : String) return String is
      F   : Ada.Text_IO.File_Type;
      Buf : Unbounded_String;
   begin
      Ada.Text_IO.Open (F, Ada.Text_IO.In_File, Path);
      while not Ada.Text_IO.End_Of_File (F) loop
         Append (Buf, Ada.Text_IO.Get_Line (F));
         if not Ada.Text_IO.End_Of_File (F) then
            Append (Buf, ASCII.LF);
         end if;
      end loop;
      Ada.Text_IO.Close (F);
      return To_String (Buf);
   end Read_File;

   --  Split Content into lines; a trailing LF does not add an empty line.
   function Split (Content : String) return String_Vectors.Vector is
      V     : String_Vectors.Vector;
      Start : Natural := Content'First;
   begin
      if Content'Length = 0 then
         return V;
      end if;
      for I in Content'Range loop
         if Content (I) = ASCII.LF then
            V.Append (To_Unbounded_String (Content (Start .. I - 1)));
            Start := I + 1;
         end if;
      end loop;
      if Start <= Content'Last then
         V.Append (To_Unbounded_String (Content (Start .. Content'Last)));
      end if;
      return V;
   end Split;

   procedure Put_Line (S : String) is
   begin
      Ada.Text_IO.Put_Line (S);
   end Put_Line;

   procedure Emit_Constant (Name : String; Content : String) is
      Lines : constant String_Vectors.Vector := Split (Content);
      Last  : constant Natural := Natural (Lines.Length);
   begin
      Put_Line ("   " & Name & " : constant String :=");
      for I in 1 .. Last loop
         declare
            Buf : Unbounded_String;
         begin
            for C of To_String (Lines (I)) loop
               Append (Buf, C);
               if C = '"' then
                  Append (Buf, '"');
               end if;
            end loop;
            if I < Last then
               Put_Line ("     """ & To_String (Buf) & """ & LF &");
            else
               Put_Line ("     """ & To_String (Buf) & """;");
            end if;
         end;
      end loop;
   end Emit_Constant;

begin
   Put_Line ("pragma Ada_2022;");
   Put_Line ("");
   Put_Line ("with Ada.Containers.Vectors;");
   Put_Line ("with Ada.Strings.Unbounded;");
   Put_Line ("");
   Put_Line ("--  Generated by tools/gen_templates -- do not edit by hand.");
   Put_Line ("--  The fixed, schema-independent code-generator templates, held as");
   Put_Line ("--  string constants so the emitters never hand-escape another language.");
   Put_Line ("package Templates is");
   Put_Line ("");
   Put_Line ("   LF : constant Character := ASCII.LF;");
   Put_Line ("");
   Emit_Constant ("C_Lexer", Read_File ("templates/lexer.c"));
   Put_Line ("");
   Emit_Constant ("C_Parse_Text", Read_File ("templates/parse_text.c"));
   Put_Line ("");
   Emit_Constant ("C_Statements", Read_File ("templates/statements.c"));
   Put_Line ("");
   Emit_Constant ("C_Stmt_Text", Read_File ("templates/stmt_text.c"));
   Put_Line ("");
   Emit_Constant ("C_Macros", Read_File ("templates/macros.c"));
   Put_Line ("");
   Emit_Constant ("C_No_Macros", Read_File ("templates/nomacros.c"));
   Put_Line ("");
   Emit_Constant ("Rust_Lexer", Read_File ("templates/lexer.rs"));
   Put_Line ("");
   Emit_Constant ("Zig_Lexer", Read_File ("templates/lexer.zig"));
   Put_Line ("");
   Emit_Constant ("Ada_Lexer", Read_File ("templates/lexer.ada"));
   Put_Line ("");
   Emit_Constant ("Conf_H", Read_File ("templates/conf.h"));
   Put_Line ("");
   Emit_Constant ("Conf_Tail_C", Read_File ("templates/conf_tail.c"));
   Put_Line ("");
   Emit_Constant ("Conf_Tail_C_Stmt", Read_File ("templates/conf_tail_stmt.c"));
   Put_Line ("");
   Emit_Constant ("Conf_H_Typed", Read_File ("templates/conf_typed.h"));
   Put_Line ("");
   Emit_Constant ("Conf_Tail_C_Typed", Read_File ("templates/conf_tail_typed.c"));
   Put_Line ("");
   Emit_Constant ("Conf_Tail_C_Typed_Stmt",
                  Read_File ("templates/conf_tail_typed_stmt.c"));
   Put_Line ("");
   Emit_Constant ("Conf_Rust", Read_File ("templates/conf.rs"));
   Put_Line ("");
   Emit_Constant ("Conf_Zig", Read_File ("templates/conf.zig"));
   Put_Line ("");
   Emit_Constant ("Conf_Ada", Read_File ("templates/conf.ada"));
   Put_Line ("");
   Emit_Constant ("Zig_Scalar", Read_File ("templates/zig_scalar.tmpl"));
   Put_Line ("");
   Emit_Constant ("Zig_Enum", Read_File ("templates/zig_enum.tmpl"));
   Put_Line ("");
   Emit_Constant ("Zig_Enum_Item", Read_File ("templates/zig_enum_item.tmpl"));
   Put_Line ("");
   Emit_Constant ("Zig_Struct", Read_File ("templates/zig_struct.tmpl"));
   Put_Line ("");
   Emit_Constant ("Zig_Struct_Item", Read_File ("templates/zig_struct_item.tmpl"));
   Put_Line ("");
   Emit_Constant ("Zig_List_Bytes", Read_File ("templates/zig_list_bytes.tmpl"));
   Put_Line ("");
   Emit_Constant ("Zig_List_Simple", Read_File ("templates/zig_list_simple.tmpl"));
   Put_Line ("");
   Emit_Constant ("Zig_List_Entry", Read_File ("templates/zig_list_entry.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_Scalar", Read_File ("templates/c_scalar.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_Enum", Read_File ("templates/c_enum.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_Enum_Item", Read_File ("templates/c_enum_item.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_Enum_Item_Last", Read_File ("templates/c_enum_item_last.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_Enum_Base", Read_File ("templates/c_enum_base.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_Struct", Read_File ("templates/c_struct.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_Idref", Read_File ("templates/c_idref.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_Kind", Read_File ("templates/c_kind.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_Line", Read_File ("templates/c_line.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_Field", Read_File ("templates/c_field.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_List_Field", Read_File ("templates/c_list_field.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_Value", Read_File ("templates/c_value.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_Entry", Read_File ("templates/c_entry.tmpl"));
   Put_Line ("");
   Emit_Constant ("C_Parser", Read_File ("templates/c_parser.tmpl"));
   Put_Line ("");
   Emit_Constant ("Rust_Scalar", Read_File ("templates/rust_scalar.tmpl"));
   Put_Line ("");
   Emit_Constant ("Rust_Enum", Read_File ("templates/rust_enum.tmpl"));
   Put_Line ("");
   Emit_Constant ("Rust_Enum_First", Read_File ("templates/rust_enum_first.tmpl"));
   Put_Line ("");
   Emit_Constant ("Rust_Enum_Item", Read_File ("templates/rust_enum_item.tmpl"));
   Put_Line ("");
   Emit_Constant ("Rust_Struct", Read_File ("templates/rust_struct.tmpl"));
   Put_Line ("");
   Emit_Constant ("Rust_Struct_Item", Read_File ("templates/rust_struct_item.tmpl"));
   Put_Line ("");
   Emit_Constant ("Rust_List_Bytes", Read_File ("templates/rust_list_bytes.tmpl"));
   Put_Line ("");
   Emit_Constant ("Rust_List_Simple", Read_File ("templates/rust_list_simple.tmpl"));
   Put_Line ("");
   Emit_Constant ("Rust_List_Entry", Read_File ("templates/rust_list_entry.tmpl"));
   Put_Line ("");
   Emit_Constant ("Rust_Parser", Read_File ("templates/rust_parser.tmpl"));
   Put_Line ("");
   Emit_Constant ("Ada_Scalar", Read_File ("templates/ada_scalar.tmpl"));
   Put_Line ("");
   Emit_Constant ("Ada_Enum", Read_File ("templates/ada_enum.tmpl"));
   Put_Line ("");
   Emit_Constant ("Ada_Struct", Read_File ("templates/ada_struct.tmpl"));
   Put_Line ("");
   Emit_Constant ("Ada_Field", Read_File ("templates/ada_field.tmpl"));
   Put_Line ("");
   Emit_Constant ("Ada_List_Subtype", Read_File ("templates/ada_list_subtype.tmpl"));
   Put_Line ("");
   Emit_Constant ("Ada_Parser_Spec", Read_File ("templates/ada_parser_spec.tmpl"));
   Put_Line ("");
   Emit_Constant ("Ada_Parser_Body", Read_File ("templates/ada_parser_body.tmpl"));
   Put_Line ("");
   Put_Line ("   --  Replace every occurrence of From in Text with To.");
   Put_Line ("   function Substitute (Text, From, To : String) return String;");
   Put_Line ("");
   Put_Line ("   Template_Error : exception;");
   Put_Line ("   --  A ${name} hole has no value, a `$` is not `$$`/`${name}`, or a");
   Put_Line ("   --  binding is set twice.");
   Put_Line ("");
   Put_Line ("   type Bindings is private;");
   Put_Line ("   --  ${name} bindings for Render.  Set adds one; Render fills holes");
   Put_Line ("   --  and marks each used; Unused names the first no hole used.");
   Put_Line ("");
   Put_Line ("   procedure Set (B : in out Bindings; Name, Value : String);");
   Put_Line ("");
   Put_Line ("   function Render (Text : String; B : in out Bindings) return String;");
   Put_Line ("");
   Put_Line ("   function Unused (B : Bindings) return String;");
   Put_Line ("");
   Put_Line ("private");
   Put_Line ("");
   Put_Line ("   type Slot is record");
   Put_Line ("      Name  : Ada.Strings.Unbounded.Unbounded_String;");
   Put_Line ("      Value : Ada.Strings.Unbounded.Unbounded_String;");
   Put_Line ("      Used  : Boolean := False;");
   Put_Line ("   end record;");
   Put_Line ("");
   Put_Line ("   package Slot_Vectors is new Ada.Containers.Vectors (Positive, Slot);");
   Put_Line ("");
   Put_Line ("   type Bindings is record");
   Put_Line ("      Slots : Slot_Vectors.Vector;");
   Put_Line ("   end record;");
   Put_Line ("");
   Put_Line ("end Templates;");
end Gen_Templates;
