#!/usr/bin/env python3
"""Turn the fixed lexer templates (templates/*.tmpl, plain text with @PLACEHOLDER@
markers) into an Ada `Templates` package whose constants hold the text as
escaped string literals.  Run from sources/hbnf/: it reads templates/ and writes
templates.ads.  Only `"` needs escaping (doubled) for Ada; backslashes are
literal, and newlines become `& LF &` concatenations.
"""
import os
import sys

TEMPLATES = {
    'C_Lexer': 'lexer.c',
    'Rust_Lexer': 'lexer.rs',
    'Zig_Lexer': 'lexer.zig',
    'Ada_Lexer': 'lexer.ada',
}


def escape(s: str) -> str:
    return s.replace('"', '""')


def emit_constant(name: str, content: str) -> str:
    lines = content.split('\n')
    if lines and lines[-1] == '':
        lines = lines[:-1]
    out = [f'   {name} : constant String :=']
    for i, line in enumerate(lines):
        suffix = ' & LF &' if i < len(lines) - 1 else ';'
        out.append(f'     "{escape(line)}"{suffix}')
    return '\n'.join(out)


def main() -> int:
    out = [
        'pragma Ada_2022;',
        '',
        '--  Generated by tools/gen_templates.py -- do not edit by hand.',
        '--  The fixed, schema-independent code-generator templates, held as',
        '--  string constants so the emitters never hand-escape another language.',
        'package Templates is',
        '',
        '   LF : constant Character := ASCII.LF;',
        '',
    ]
    for name, fname in TEMPLATES.items():
        with open(os.path.join('templates', fname)) as f:
            content = f.read()
        out.append(emit_constant(name, content))
        out.append('')
    out.append('   --  Replace every occurrence of From in Text with To.')
    out.append('   function Substitute (Text, From, To : String) return String;')
    out.append('')
    out.append('end Templates;')
    out.append('')
    sys.stdout.write('\n'.join(out))
    return 0


if __name__ == '__main__':
    sys.exit(main())
